// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type CreateNoteRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreateNoteResponse struct {
	Note Note `json:"note"`
}

type CreateTeamRequest struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CreateTeamResponse struct {
	Team Team `json:"team"`
}

type DeleteNoteRequest struct {
	NoteId string `path:"note_id"` // 路径参数
}

type DeleteNoteResponse struct {
	Success bool `json:"success"`
}

type DeleteTeamRequest struct {
	TeamId string `path:"team_id"`
}

type DeleteTeamResponse struct {
	Success bool `json:"success"`
}

type ExitTeamRequest struct {
	TeamId string `path:"team_id"`
}

type ExitTeamResponse struct {
	Success bool `json:"success"`
}

type GetNoteRequest struct {
	NoteId string `path:"note_id"` // 路径参数
}

type GetNoteResponse struct {
	Note Note `json:"note"`
}

type GetTeamRequest struct {
	TeamId string `path:"team_id"`
}

type GetTeamResponse struct {
	Team Team `json:"team"`
}

type GrantNotePermissionRequest struct {
	NoteId       string `path:"note_id"`
	TargetUserId string `json:"target_user_id"`
	Level        int32  `json:"level"`
}

type GrantNotePermissionResponse struct {
	Permission UserPermission `json:"permission"`
}

type JoinTeamRequest struct {
	TeamId string `path:"team_id"`
}

type JoinTeamResponse struct {
	Success bool `json:"success"`
}

type ListNotePermissionsRequest struct {
	NoteId string `path:"note_id"`
}

type ListNotePermissionsResponse struct {
	Permissions []UserPermission `json:"permissions"`
}

type ListNotesRequest struct {
	PaginationRequest
	OwnerId string `json:"owner_id"`
}

type ListNotesResponse struct {
	Notes      []Note             `json:"notes"`
	Pagination PaginationResponse `json:"pagination"`
}

type ListTeamMembersRequest struct {
	TeamId string `path:"team_id"`
	PaginationRequest
}

type ListTeamMembersResponse struct {
	Members    []TeamMember       `json:"members"`
	Pagination PaginationResponse `json:"pagination"`
}

type Note struct {
	NoteId    string `json:"note_id"`
	OwnerId   string `json:"owner_id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Version   int32  `json:"version"`
	CreatedAt string `json:"created_at"` // RFC3339 格式
	UpdatedAt string `json:"updated_at"`
}

type PaginationRequest struct {
	Page     int32 `json:"page"`
	PageSize int32 `json:"page_size"`
}

type PaginationResponse struct {
	Total    int32 `json:"total"`
	Page     int32 `json:"page"`
	PageSize int32 `json:"page_size"`
	HasMore  bool  `json:"has_more"`
}

type RevokeNotePermissionRequest struct {
	NoteId       string `path:"note_id"`
	TargetUserId string `path:"target_user_id"` // 路径参数
}

type RevokeNotePermissionResponse struct {
	Success bool `json:"success"`
}

type Team struct {
	TeamId      string `json:"team_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	OwnerId     string `json:"owner_id"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type TeamMember struct {
	Id       string `json:"id"`
	TeamId   string `json:"team_id"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
	JoinedAt string `json:"joined_at"`
}

type UpdateNoteRequest struct {
	NoteId  string `path:"note_id"` // 路径参数
	Title   string `json:"title"`
	Content string `json:"content"`
	Version int32  `json:"version"`
}

type UpdateNoteResponse struct {
	Note Note `json:"note"`
}

type UpdateTeamRequest struct {
	TeamId      string `path:"team_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type UpdateTeamResponse struct {
	Team Team `json:"team"`
}

type UserPermission struct {
	PermissionId string `json:"permission_id"`
	NoteId       string `json:"note_id"`
	UserId       string `json:"user_id"`
	Level        int32  `json:"level"` // 对应 PermissionLevel 枚举
	GrantedBy    string `json:"granted_by"`
	CreatedAt    string `json:"created_at"`
}
