// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: user.proto

package userservice

import (
	"context"

	"SyncNote/rebuild/user/rpc/pb/userrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EditUserInfoReq       = userrpc.EditUserInfoReq
	Empty                 = userrpc.Empty
	GetUserInfoByEmailReq = userrpc.GetUserInfoByEmailReq
	GetUserInfoReq        = userrpc.GetUserInfoReq
	GetUserInfoResp       = userrpc.GetUserInfoResp
	UserInfo              = userrpc.UserInfo

	UserService interface {
		EditUserInfo(ctx context.Context, in *EditUserInfoReq, opts ...grpc.CallOption) (*Empty, error)
		GetUserInfoById(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		GetUserInfoByEmail(ctx context.Context, in *GetUserInfoByEmailReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) EditUserInfo(ctx context.Context, in *EditUserInfoReq, opts ...grpc.CallOption) (*Empty, error) {
	client := userrpc.NewUserServiceClient(m.cli.Conn())
	return client.EditUserInfo(ctx, in, opts...)
}

func (m *defaultUserService) GetUserInfoById(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := userrpc.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfoById(ctx, in, opts...)
}

func (m *defaultUserService) GetUserInfoByEmail(ctx context.Context, in *GetUserInfoByEmailReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := userrpc.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfoByEmail(ctx, in, opts...)
}
