// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"SyncNote/auth/api/internal/svc"
	"SyncNote/pkg/httpx"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodOptions,
				Path:    "/auth/login",
				Handler: httpx.PreflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/auth/register",
				Handler: httpx.PreflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)
}
