// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: syncnote.proto

package server

import (
	"context"

	"SyncNote/rebuild/syncnote/rpc/internal/rpc/internal/logic"
	"SyncNote/rebuild/syncnote/rpc/internal/rpc/internal/svc"
	"SyncNote/rebuild/syncnote/rpc/internal/rpc/syncnoterpc"
)

type NoteServiceServer struct {
	svcCtx *svc.ServiceContext
	syncnoterpc.UnimplementedNoteServiceServer
}

func NewNoteServiceServer(svcCtx *svc.ServiceContext) *NoteServiceServer {
	return &NoteServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *NoteServiceServer) CreateNote(ctx context.Context, in *syncnoterpc.CreateNoteRequest) (*syncnoterpc.CreateNoteResponse, error) {
	l := logic.NewCreateNoteLogic(ctx, s.svcCtx)
	return l.CreateNote(in)
}

func (s *NoteServiceServer) GetNote(ctx context.Context, in *syncnoterpc.GetNoteRequest) (*syncnoterpc.GetNoteResponse, error) {
	l := logic.NewGetNoteLogic(ctx, s.svcCtx)
	return l.GetNote(in)
}

func (s *NoteServiceServer) UpdateNote(ctx context.Context, in *syncnoterpc.UpdateNoteRequest) (*syncnoterpc.UpdateNoteResponse, error) {
	l := logic.NewUpdateNoteLogic(ctx, s.svcCtx)
	return l.UpdateNote(in)
}

func (s *NoteServiceServer) DeleteNote(ctx context.Context, in *syncnoterpc.DeleteNoteRequest) (*syncnoterpc.DeleteNoteResponse, error) {
	l := logic.NewDeleteNoteLogic(ctx, s.svcCtx)
	return l.DeleteNote(in)
}

func (s *NoteServiceServer) ListNotes(ctx context.Context, in *syncnoterpc.ListNotesRequest) (*syncnoterpc.ListNotesResponse, error) {
	l := logic.NewListNotesLogic(ctx, s.svcCtx)
	return l.ListNotes(in)
}

func (s *NoteServiceServer) GrantNotePermission(ctx context.Context, in *syncnoterpc.GrantNotePermissionRequest) (*syncnoterpc.GrantNotePermissionResponse, error) {
	l := logic.NewGrantNotePermissionLogic(ctx, s.svcCtx)
	return l.GrantNotePermission(in)
}

func (s *NoteServiceServer) RevokeNotePermission(ctx context.Context, in *syncnoterpc.RevokeNotePermissionRequest) (*syncnoterpc.RevokeNotePermissionResponse, error) {
	l := logic.NewRevokeNotePermissionLogic(ctx, s.svcCtx)
	return l.RevokeNotePermission(in)
}

func (s *NoteServiceServer) ListNotePermissions(ctx context.Context, in *syncnoterpc.ListNotePermissionsRequest) (*syncnoterpc.ListNotePermissionsResponse, error) {
	l := logic.NewListNotePermissionsLogic(ctx, s.svcCtx)
	return l.ListNotePermissions(in)
}

func (s *NoteServiceServer) CreateTeam(ctx context.Context, in *syncnoterpc.CreateTeamRequest) (*syncnoterpc.CreateTeamResponse, error) {
	l := logic.NewCreateTeamLogic(ctx, s.svcCtx)
	return l.CreateTeam(in)
}

func (s *NoteServiceServer) GetTeam(ctx context.Context, in *syncnoterpc.GetTeamRequest) (*syncnoterpc.GetTeamResponse, error) {
	l := logic.NewGetTeamLogic(ctx, s.svcCtx)
	return l.GetTeam(in)
}

func (s *NoteServiceServer) UpdateTeam(ctx context.Context, in *syncnoterpc.UpdateTeamRequest) (*syncnoterpc.UpdateTeamResponse, error) {
	l := logic.NewUpdateTeamLogic(ctx, s.svcCtx)
	return l.UpdateTeam(in)
}

func (s *NoteServiceServer) DeleteTeam(ctx context.Context, in *syncnoterpc.DeleteTeamRequest) (*syncnoterpc.DeleteTeamResponse, error) {
	l := logic.NewDeleteTeamLogic(ctx, s.svcCtx)
	return l.DeleteTeam(in)
}

func (s *NoteServiceServer) JoinTeam(ctx context.Context, in *syncnoterpc.JoinTeamRequest) (*syncnoterpc.JoinTeamResponse, error) {
	l := logic.NewJoinTeamLogic(ctx, s.svcCtx)
	return l.JoinTeam(in)
}

func (s *NoteServiceServer) ExitTeam(ctx context.Context, in *syncnoterpc.ExitTeamRequest) (*syncnoterpc.ExitTeamResponse, error) {
	l := logic.NewExitTeamLogic(ctx, s.svcCtx)
	return l.ExitTeam(in)
}

func (s *NoteServiceServer) ListTeamMembers(ctx context.Context, in *syncnoterpc.ListTeamMembersRequest) (*syncnoterpc.ListTeamMembersResponse, error) {
	l := logic.NewListTeamMembersLogic(ctx, s.svcCtx)
	return l.ListTeamMembers(in)
}
