// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	notesFieldNames          = builder.RawFieldNames(&Notes{})
	notesRows                = strings.Join(notesFieldNames, ",")
	notesRowsExpectAutoSet   = strings.Join(stringx.Remove(notesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	notesRowsWithPlaceHolder = strings.Join(stringx.Remove(notesFieldNames, "`note_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheNotesNoteIdPrefix = "cache:notes:noteId:"
)

type (
	notesModel interface {
		Insert(ctx context.Context, data *Notes) (sql.Result, error)
		FindOne(ctx context.Context, noteId string) (*Notes, error)
		Update(ctx context.Context, data *Notes) error
		Delete(ctx context.Context, noteId string) error
	}

	defaultNotesModel struct {
		sqlc.CachedConn
		table string
	}

	Notes struct {
		NoteId       string `db:"note_id"`       // 笔记唯一ID
		UserId       string `db:"user_id"`       // 所属用户ID
		Title        string `db:"title"`         // 笔记标题
		Content      string `db:"content"`       // 笔记内容
		Version      uint64 `db:"version"`       // 版本号
		LastModified int64  `db:"last_modified"` // 最后修改时间戳
		IsDeleted    int64  `db:"is_deleted"`    // 是否删除 0:否 1:是
		CreatedAt    int64  `db:"created_at"`    // 创建时间戳
	}
)

func newNotesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultNotesModel {
	return &defaultNotesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`notes`",
	}
}

func (m *defaultNotesModel) Delete(ctx context.Context, noteId string) error {
	notesNoteIdKey := fmt.Sprintf("%s%v", cacheNotesNoteIdPrefix, noteId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `note_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, noteId)
	}, notesNoteIdKey)
	return err
}

func (m *defaultNotesModel) FindOne(ctx context.Context, noteId string) (*Notes, error) {
	notesNoteIdKey := fmt.Sprintf("%s%v", cacheNotesNoteIdPrefix, noteId)
	var resp Notes
	err := m.QueryRowCtx(ctx, &resp, notesNoteIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `note_id` = ? limit 1", notesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, noteId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNotesModel) Insert(ctx context.Context, data *Notes) (sql.Result, error) {
	notesNoteIdKey := fmt.Sprintf("%s%v", cacheNotesNoteIdPrefix, data.NoteId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, notesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.NoteId, data.UserId, data.Title, data.Content, data.Version, data.LastModified, data.IsDeleted)
	}, notesNoteIdKey)
	return ret, err
}

func (m *defaultNotesModel) Update(ctx context.Context, data *Notes) error {
	notesNoteIdKey := fmt.Sprintf("%s%v", cacheNotesNoteIdPrefix, data.NoteId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `note_id` = ?", m.table, notesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Title, data.Content, data.Version, data.LastModified, data.IsDeleted, data.NoteId)
	}, notesNoteIdKey)
	return err
}

func (m *defaultNotesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheNotesNoteIdPrefix, primary)
}

func (m *defaultNotesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `note_id` = ? limit 1", notesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultNotesModel) tableName() string {
	return m.table
}
