// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: syncNoterpc.proto

package syncnoterpcclient

import (
	"context"

	"SyncNote/syncnote/rpc/pb/syncnoterpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CollaborationEvent  = syncnoterpc.CollaborationEvent
	CreateNoteReq       = syncnoterpc.CreateNoteReq
	GetNoteEventsReq    = syncnoterpc.GetNoteEventsReq
	GetNoteEventsResp   = syncnoterpc.GetNoteEventsResp
	GrantPermissionReq  = syncnoterpc.GrantPermissionReq
	ListMyTeamsReq      = syncnoterpc.ListMyTeamsReq
	ListMyTeamsResp     = syncnoterpc.ListMyTeamsResp
	ListPermissionsReq  = syncnoterpc.ListPermissionsReq
	ListPermissionsResp = syncnoterpc.ListPermissionsResp
	NoteReq             = syncnoterpc.NoteReq
	NoteResp            = syncnoterpc.NoteResp
	NoteSummary         = syncnoterpc.NoteSummary
	PermissionInfo      = syncnoterpc.PermissionInfo
	PermissionResp      = syncnoterpc.PermissionResp
	RevokePermissionReq = syncnoterpc.RevokePermissionReq
	SaveNoteReq         = syncnoterpc.SaveNoteReq
	SaveNoteResp        = syncnoterpc.SaveNoteResp
	TeamInfo            = syncnoterpc.TeamInfo
	UserNotesReq        = syncnoterpc.UserNotesReq
	UserNotesResp       = syncnoterpc.UserNotesResp

	Syncnoterpc interface {
		// --- Core Note Operations ---
		CreateNote(ctx context.Context, in *CreateNoteReq, opts ...grpc.CallOption) (*NoteResp, error)
		GetNote(ctx context.Context, in *NoteReq, opts ...grpc.CallOption) (*NoteResp, error)
		SaveNote(ctx context.Context, in *SaveNoteReq, opts ...grpc.CallOption) (*SaveNoteResp, error)
		GetUserNotes(ctx context.Context, in *UserNotesReq, opts ...grpc.CallOption) (*UserNotesResp, error)
		// --- Permission Management (对应 note_permissions 表) ---
		GrantPermission(ctx context.Context, in *GrantPermissionReq, opts ...grpc.CallOption) (*PermissionResp, error)
		// 撤销权限
		RevokePermission(ctx context.Context, in *RevokePermissionReq, opts ...grpc.CallOption) (*PermissionResp, error)
		// 获取笔记的所有权限列表
		ListPermissions(ctx context.Context, in *ListPermissionsReq, opts ...grpc.CallOption) (*ListPermissionsResp, error)
		// --- Collaboration History (对应 collaboration_events 表) ---
		GetNoteEvents(ctx context.Context, in *GetNoteEventsReq, opts ...grpc.CallOption) (*GetNoteEventsResp, error)
		// --- Team Membership ---
		ListMyTeams(ctx context.Context, in *ListMyTeamsReq, opts ...grpc.CallOption) (*ListMyTeamsResp, error)
	}

	defaultSyncnoterpc struct {
		cli zrpc.Client
	}
)

func NewSyncnoterpc(cli zrpc.Client) Syncnoterpc {
	return &defaultSyncnoterpc{
		cli: cli,
	}
}

// --- Core Note Operations ---
func (m *defaultSyncnoterpc) CreateNote(ctx context.Context, in *CreateNoteReq, opts ...grpc.CallOption) (*NoteResp, error) {
	client := syncnoterpc.NewSyncnoterpcClient(m.cli.Conn())
	return client.CreateNote(ctx, in, opts...)
}

func (m *defaultSyncnoterpc) GetNote(ctx context.Context, in *NoteReq, opts ...grpc.CallOption) (*NoteResp, error) {
	client := syncnoterpc.NewSyncnoterpcClient(m.cli.Conn())
	return client.GetNote(ctx, in, opts...)
}

func (m *defaultSyncnoterpc) SaveNote(ctx context.Context, in *SaveNoteReq, opts ...grpc.CallOption) (*SaveNoteResp, error) {
	client := syncnoterpc.NewSyncnoterpcClient(m.cli.Conn())
	return client.SaveNote(ctx, in, opts...)
}

func (m *defaultSyncnoterpc) GetUserNotes(ctx context.Context, in *UserNotesReq, opts ...grpc.CallOption) (*UserNotesResp, error) {
	client := syncnoterpc.NewSyncnoterpcClient(m.cli.Conn())
	return client.GetUserNotes(ctx, in, opts...)
}

// --- Permission Management (对应 note_permissions 表) ---
func (m *defaultSyncnoterpc) GrantPermission(ctx context.Context, in *GrantPermissionReq, opts ...grpc.CallOption) (*PermissionResp, error) {
	client := syncnoterpc.NewSyncnoterpcClient(m.cli.Conn())
	return client.GrantPermission(ctx, in, opts...)
}

// 撤销权限
func (m *defaultSyncnoterpc) RevokePermission(ctx context.Context, in *RevokePermissionReq, opts ...grpc.CallOption) (*PermissionResp, error) {
	client := syncnoterpc.NewSyncnoterpcClient(m.cli.Conn())
	return client.RevokePermission(ctx, in, opts...)
}

// 获取笔记的所有权限列表
func (m *defaultSyncnoterpc) ListPermissions(ctx context.Context, in *ListPermissionsReq, opts ...grpc.CallOption) (*ListPermissionsResp, error) {
	client := syncnoterpc.NewSyncnoterpcClient(m.cli.Conn())
	return client.ListPermissions(ctx, in, opts...)
}

// --- Collaboration History (对应 collaboration_events 表) ---
func (m *defaultSyncnoterpc) GetNoteEvents(ctx context.Context, in *GetNoteEventsReq, opts ...grpc.CallOption) (*GetNoteEventsResp, error) {
	client := syncnoterpc.NewSyncnoterpcClient(m.cli.Conn())
	return client.GetNoteEvents(ctx, in, opts...)
}

// --- Team Membership ---
func (m *defaultSyncnoterpc) ListMyTeams(ctx context.Context, in *ListMyTeamsReq, opts ...grpc.CallOption) (*ListMyTeamsResp, error) {
	client := syncnoterpc.NewSyncnoterpcClient(m.cli.Conn())
	return client.ListMyTeams(ctx, in, opts...)
}
