// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	"SyncNote/syncnote/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/note/:noteId",
					Handler: GetNoteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/note/create",
					Handler: CreateNoteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/note/save",
					Handler: SaveNoteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/user/notes",
					Handler: GetUserNotesHandler(serverCtx),
				},
			}...,
		),
	)
}
