// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"SyncNote/syncnote/api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/note/:noteId",
				Handler: GetNoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/note/create",
				Handler: CreateNoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/note/save",
				Handler: SaveNoteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/:userId/notes",
				Handler: GetUserNotesHandler(serverCtx),
			},
		},
	)
}
