// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	"SyncNote/rebuild/syncnote/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建笔记
				Method:  http.MethodPost,
				Path:    "/api/v1/notes",
				Handler: CreateNoteHandler(serverCtx),
			},
			{
				// 获取笔记列表
				Method:  http.MethodGet,
				Path:    "/api/v1/notes",
				Handler: ListNotesHandler(serverCtx),
			},
			{
				// 获取笔记详情
				Method:  http.MethodGet,
				Path:    "/api/v1/notes/:note_id",
				Handler: GetNoteHandler(serverCtx),
			},
			{
				// 更新笔记
				Method:  http.MethodPut,
				Path:    "/api/v1/notes/:note_id",
				Handler: UpdateNoteHandler(serverCtx),
			},
			{
				// 删除笔记
				Method:  http.MethodDelete,
				Path:    "/api/v1/notes/:note_id",
				Handler: DeleteNoteHandler(serverCtx),
			},
			{
				// 授予笔记权限
				Method:  http.MethodPost,
				Path:    "/api/v1/notes/:note_id/permissions",
				Handler: GrantNotePermissionHandler(serverCtx),
			},
			{
				// 获取笔记权限列表
				Method:  http.MethodGet,
				Path:    "/api/v1/notes/:note_id/permissions",
				Handler: ListNotePermissionsHandler(serverCtx),
			},
			{
				// 撤销笔记权限
				Method:  http.MethodDelete,
				Path:    "/api/v1/notes/:note_id/permissions/:target_user_id",
				Handler: RevokeNotePermissionHandler(serverCtx),
			},
			{
				// 创建团队
				Method:  http.MethodPost,
				Path:    "/api/v1/teams",
				Handler: CreateTeamHandler(serverCtx),
			},
			{
				// 获取团队详情
				Method:  http.MethodGet,
				Path:    "/api/v1/teams/:team_id",
				Handler: GetTeamHandler(serverCtx),
			},
			{
				// 更新团队
				Method:  http.MethodPut,
				Path:    "/api/v1/teams/:team_id",
				Handler: UpdateTeamHandler(serverCtx),
			},
			{
				// 删除团队
				Method:  http.MethodDelete,
				Path:    "/api/v1/teams/:team_id",
				Handler: DeleteTeamHandler(serverCtx),
			},
			{
				// 退出团队
				Method:  http.MethodPost,
				Path:    "/api/v1/teams/:team_id/exit",
				Handler: ExitTeamHandler(serverCtx),
			},
			{
				// 加入团队
				Method:  http.MethodPost,
				Path:    "/api/v1/teams/:team_id/join",
				Handler: JoinTeamHandler(serverCtx),
			},
			{
				// 获取团队成员列表
				Method:  http.MethodGet,
				Path:    "/api/v1/teams/:team_id/members",
				Handler: ListTeamMembersHandler(serverCtx),
			},
		},
	)
}
