// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: syncNoterpc.proto

package server

import (
	"context"

	"SyncNote/syncnote/rpc/internal/logic"
	"SyncNote/syncnote/rpc/internal/svc"
	"SyncNote/syncnote/rpc/pb/syncnoterpc"
)

type SyncnoterpcServer struct {
	svcCtx *svc.ServiceContext
	syncnoterpc.UnimplementedSyncnoterpcServer
}

func NewSyncnoterpcServer(svcCtx *svc.ServiceContext) *SyncnoterpcServer {
	return &SyncnoterpcServer{
		svcCtx: svcCtx,
	}
}

// --- Core Note Operations ---
func (s *SyncnoterpcServer) CreateNote(ctx context.Context, in *syncnoterpc.CreateNoteReq) (*syncnoterpc.NoteResp, error) {
	l := logic.NewCreateNoteLogic(ctx, s.svcCtx)
	return l.CreateNote(in)
}

func (s *SyncnoterpcServer) GetNote(ctx context.Context, in *syncnoterpc.NoteReq) (*syncnoterpc.NoteResp, error) {
	l := logic.NewGetNoteLogic(ctx, s.svcCtx)
	return l.GetNote(in)
}

func (s *SyncnoterpcServer) SaveNote(ctx context.Context, in *syncnoterpc.SaveNoteReq) (*syncnoterpc.SaveNoteResp, error) {
	l := logic.NewSaveNoteLogic(ctx, s.svcCtx)
	return l.SaveNote(in)
}

func (s *SyncnoterpcServer) GetUserNotes(ctx context.Context, in *syncnoterpc.UserNotesReq) (*syncnoterpc.UserNotesResp, error) {
	l := logic.NewGetUserNotesLogic(ctx, s.svcCtx)
	return l.GetUserNotes(in)
}

// --- Permission Management (对应 note_permissions 表) ---
func (s *SyncnoterpcServer) GrantPermission(ctx context.Context, in *syncnoterpc.GrantPermissionReq) (*syncnoterpc.PermissionResp, error) {
	l := logic.NewGrantPermissionLogic(ctx, s.svcCtx)
	return l.GrantPermission(in)
}

// 撤销权限
func (s *SyncnoterpcServer) RevokePermission(ctx context.Context, in *syncnoterpc.RevokePermissionReq) (*syncnoterpc.PermissionResp, error) {
	l := logic.NewRevokePermissionLogic(ctx, s.svcCtx)
	return l.RevokePermission(in)
}

// 获取笔记的所有权限列表
func (s *SyncnoterpcServer) ListPermissions(ctx context.Context, in *syncnoterpc.ListPermissionsReq) (*syncnoterpc.ListPermissionsResp, error) {
	l := logic.NewListPermissionsLogic(ctx, s.svcCtx)
	return l.ListPermissions(in)
}

// --- Collaboration History (对应 collaboration_events 表) ---
func (s *SyncnoterpcServer) GetNoteEvents(ctx context.Context, in *syncnoterpc.GetNoteEventsReq) (*syncnoterpc.GetNoteEventsResp, error) {
	l := logic.NewGetNoteEventsLogic(ctx, s.svcCtx)
	return l.GetNoteEvents(in)
}

// --- Team Membership ---
func (s *SyncnoterpcServer) ListMyTeams(ctx context.Context, in *syncnoterpc.ListMyTeamsReq) (*syncnoterpc.ListMyTeamsResp, error) {
	l := logic.NewListMyTeamsLogic(ctx, s.svcCtx)
	return l.ListMyTeams(in)
}
