// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: syncNoterpc.proto

package server

import (
	"SyncNote/syncnote/rpc/internal/logic"
	"SyncNote/syncnote/rpc/internal/svc"
	"SyncNote/syncnote/rpc/pb/syncnoterpc"
	"context"
)

type SyncnoterpcServer struct {
	svcCtx *svc.ServiceContext
	syncnoterpc.UnimplementedSyncnoterpcServer
}

func NewSyncnoterpcServer(svcCtx *svc.ServiceContext) *SyncnoterpcServer {
	return &SyncnoterpcServer{
		svcCtx: svcCtx,
	}
}

func (s *SyncnoterpcServer) CreateNote(ctx context.Context, in *syncnoterpc.CreateNoteReq) (*syncnoterpc.NoteResp, error) {
	l := logic.NewCreateNoteLogic(ctx, s.svcCtx)
	return l.CreateNote(in)
}

func (s *SyncnoterpcServer) GetNote(ctx context.Context, in *syncnoterpc.NoteReq) (*syncnoterpc.NoteResp, error) {
	l := logic.NewGetNoteLogic(ctx, s.svcCtx)
	return l.GetNote(in)
}

func (s *SyncnoterpcServer) SaveNote(ctx context.Context, in *syncnoterpc.SaveNoteReq) (*syncnoterpc.SaveNoteResp, error) {
	l := logic.NewSaveNoteLogic(ctx, s.svcCtx)
	return l.SaveNote(in)
}

func (s *SyncnoterpcServer) GetUserNotes(ctx context.Context, in *syncnoterpc.UserNotesReq) (*syncnoterpc.UserNotesResp, error) {
	l := logic.NewGetUserNotesLogic(ctx, s.svcCtx)
	return l.GetUserNotes(in)
}
