// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type CreateNoteReq struct {
	Title   string `json:"title"`
	Content string `json:"content,omitempty"`
}

type NoteReq struct {
	NoteId string `path:"noteId"`
}

type NoteResp struct {
	NoteId       string
	UserId       string
	Title        string
	Content      string
	Version      int64
	LastModified int64
}

type NoteSummary struct {
	NoteId       string
	Title        string
	Version      int64
	LastModified int64
}

type SaveNoteReq struct {
	NoteId          string `json:"noteId"`
	Content         string `json:"content"`
	ExpectedVersion int64  `json:"expectedVersion"`
}

type SaveNoteResp struct {
	Success       bool
	Code          string
	Message       string
	Note          *NoteResp `json:"note,omitempty"`
	LatestVersion int64     `json:"latestVersion,omitempty"`
}

type UserNotesReq struct {
}

type UserNotesResp struct {
	Notes []NoteSummary
}
