// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: user.proto

package server

import (
	"context"

	"SyncNote/rebuild/user/rpc/internal/logic"
	"SyncNote/rebuild/user/rpc/internal/svc"
	"SyncNote/rebuild/user/rpc/pb/userrpc"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	userrpc.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) EditUserInfo(ctx context.Context, in *userrpc.EditUserInfoReq) (*userrpc.Empty, error) {
	l := logic.NewEditUserInfoLogic(ctx, s.svcCtx)
	return l.EditUserInfo(in)
}

func (s *UserServiceServer) GetUserInfoById(ctx context.Context, in *userrpc.GetUserInfoReq) (*userrpc.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoByIdLogic(ctx, s.svcCtx)
	return l.GetUserInfoById(in)
}

func (s *UserServiceServer) GetUserInfoByEmail(ctx context.Context, in *userrpc.GetUserInfoByEmailReq) (*userrpc.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoByEmailLogic(ctx, s.svcCtx)
	return l.GetUserInfoByEmail(in)
}
