// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: syncnote.proto

package syncnoteservice

import (
	"context"

	"SyncNote/rebuild/syncnote/rpc/pb/syncnoterpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateNoteRequest            = syncnoterpc.CreateNoteRequest
	CreateNoteResponse           = syncnoterpc.CreateNoteResponse
	CreateTeamRequest            = syncnoterpc.CreateTeamRequest
	CreateTeamResponse           = syncnoterpc.CreateTeamResponse
	DeleteNoteRequest            = syncnoterpc.DeleteNoteRequest
	DeleteNoteResponse           = syncnoterpc.DeleteNoteResponse
	DeleteTeamRequest            = syncnoterpc.DeleteTeamRequest
	DeleteTeamResponse           = syncnoterpc.DeleteTeamResponse
	ExitTeamRequest              = syncnoterpc.ExitTeamRequest
	ExitTeamResponse             = syncnoterpc.ExitTeamResponse
	GetNoteRequest               = syncnoterpc.GetNoteRequest
	GetNoteResponse              = syncnoterpc.GetNoteResponse
	GetTeamRequest               = syncnoterpc.GetTeamRequest
	GetTeamResponse              = syncnoterpc.GetTeamResponse
	GrantNotePermissionRequest   = syncnoterpc.GrantNotePermissionRequest
	GrantNotePermissionResponse  = syncnoterpc.GrantNotePermissionResponse
	JoinTeamRequest              = syncnoterpc.JoinTeamRequest
	JoinTeamResponse             = syncnoterpc.JoinTeamResponse
	Note                         = syncnoterpc.Note
	RevokeNotePermissionRequest  = syncnoterpc.RevokeNotePermissionRequest
	RevokeNotePermissionResponse = syncnoterpc.RevokeNotePermissionResponse
	Team                         = syncnoterpc.Team
	TeamMember                   = syncnoterpc.TeamMember
	UpdateNoteRequest            = syncnoterpc.UpdateNoteRequest
	UpdateNoteResponse           = syncnoterpc.UpdateNoteResponse
	UpdateTeamRequest            = syncnoterpc.UpdateTeamRequest
	UpdateTeamResponse           = syncnoterpc.UpdateTeamResponse
	UserPermission               = syncnoterpc.UserPermission

	SyncnoteService interface {
		CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error)
		GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error)
		UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...grpc.CallOption) (*UpdateNoteResponse, error)
		DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error)
		GrantNotePermission(ctx context.Context, in *GrantNotePermissionRequest, opts ...grpc.CallOption) (*GrantNotePermissionResponse, error)
		RevokeNotePermission(ctx context.Context, in *RevokeNotePermissionRequest, opts ...grpc.CallOption) (*RevokeNotePermissionResponse, error)
		CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error)
		GetTeam(ctx context.Context, in *GetTeamRequest, opts ...grpc.CallOption) (*GetTeamResponse, error)
		UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*UpdateTeamResponse, error)
		DeleteTeam(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*DeleteTeamResponse, error)
		JoinTeam(ctx context.Context, in *JoinTeamRequest, opts ...grpc.CallOption) (*JoinTeamResponse, error)
		ExitTeam(ctx context.Context, in *ExitTeamRequest, opts ...grpc.CallOption) (*ExitTeamResponse, error)
	}

	defaultSyncnoteService struct {
		cli zrpc.Client
	}
)

func NewSyncnoteService(cli zrpc.Client) SyncnoteService {
	return &defaultSyncnoteService{
		cli: cli,
	}
}

func (m *defaultSyncnoteService) CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error) {
	client := syncnoterpc.NewSyncnoteServiceClient(m.cli.Conn())
	return client.CreateNote(ctx, in, opts...)
}

func (m *defaultSyncnoteService) GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error) {
	client := syncnoterpc.NewSyncnoteServiceClient(m.cli.Conn())
	return client.GetNote(ctx, in, opts...)
}

func (m *defaultSyncnoteService) UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...grpc.CallOption) (*UpdateNoteResponse, error) {
	client := syncnoterpc.NewSyncnoteServiceClient(m.cli.Conn())
	return client.UpdateNote(ctx, in, opts...)
}

func (m *defaultSyncnoteService) DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error) {
	client := syncnoterpc.NewSyncnoteServiceClient(m.cli.Conn())
	return client.DeleteNote(ctx, in, opts...)
}

func (m *defaultSyncnoteService) GrantNotePermission(ctx context.Context, in *GrantNotePermissionRequest, opts ...grpc.CallOption) (*GrantNotePermissionResponse, error) {
	client := syncnoterpc.NewSyncnoteServiceClient(m.cli.Conn())
	return client.GrantNotePermission(ctx, in, opts...)
}

func (m *defaultSyncnoteService) RevokeNotePermission(ctx context.Context, in *RevokeNotePermissionRequest, opts ...grpc.CallOption) (*RevokeNotePermissionResponse, error) {
	client := syncnoterpc.NewSyncnoteServiceClient(m.cli.Conn())
	return client.RevokeNotePermission(ctx, in, opts...)
}

func (m *defaultSyncnoteService) CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error) {
	client := syncnoterpc.NewSyncnoteServiceClient(m.cli.Conn())
	return client.CreateTeam(ctx, in, opts...)
}

func (m *defaultSyncnoteService) GetTeam(ctx context.Context, in *GetTeamRequest, opts ...grpc.CallOption) (*GetTeamResponse, error) {
	client := syncnoterpc.NewSyncnoteServiceClient(m.cli.Conn())
	return client.GetTeam(ctx, in, opts...)
}

func (m *defaultSyncnoteService) UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*UpdateTeamResponse, error) {
	client := syncnoterpc.NewSyncnoteServiceClient(m.cli.Conn())
	return client.UpdateTeam(ctx, in, opts...)
}

func (m *defaultSyncnoteService) DeleteTeam(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*DeleteTeamResponse, error) {
	client := syncnoterpc.NewSyncnoteServiceClient(m.cli.Conn())
	return client.DeleteTeam(ctx, in, opts...)
}

func (m *defaultSyncnoteService) JoinTeam(ctx context.Context, in *JoinTeamRequest, opts ...grpc.CallOption) (*JoinTeamResponse, error) {
	client := syncnoterpc.NewSyncnoteServiceClient(m.cli.Conn())
	return client.JoinTeam(ctx, in, opts...)
}

func (m *defaultSyncnoteService) ExitTeam(ctx context.Context, in *ExitTeamRequest, opts ...grpc.CallOption) (*ExitTeamResponse, error) {
	client := syncnoterpc.NewSyncnoteServiceClient(m.cli.Conn())
	return client.ExitTeam(ctx, in, opts...)
}
