// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: SyncNote.proto

package syncnoterpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 编辑操作定义
type EditOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpType        string                 `protobuf:"bytes,1,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	Start         int32                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End           int32                  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditOperation) Reset() {
	*x = EditOperation{}
	mi := &file_SyncNote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditOperation) ProtoMessage() {}

func (x *EditOperation) ProtoReflect() protoreflect.Message {
	mi := &file_SyncNote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditOperation.ProtoReflect.Descriptor instead.
func (*EditOperation) Descriptor() ([]byte, []int) {
	return file_SyncNote_proto_rawDescGZIP(), []int{0}
}

func (x *EditOperation) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *EditOperation) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *EditOperation) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *EditOperation) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 笔记请求
type NoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteReq) Reset() {
	*x = NoteReq{}
	mi := &file_SyncNote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteReq) ProtoMessage() {}

func (x *NoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_SyncNote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteReq.ProtoReflect.Descriptor instead.
func (*NoteReq) Descriptor() ([]byte, []int) {
	return file_SyncNote_proto_rawDescGZIP(), []int{1}
}

func (x *NoteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoteReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NoteReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// 笔记响应
type NoteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LastModified  int64                  `protobuf:"varint,7,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteResp) Reset() {
	*x = NoteResp{}
	mi := &file_SyncNote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteResp) ProtoMessage() {}

func (x *NoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_SyncNote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteResp.ProtoReflect.Descriptor instead.
func (*NoteResp) Descriptor() ([]byte, []int) {
	return file_SyncNote_proto_rawDescGZIP(), []int{2}
}

func (x *NoteResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoteResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NoteResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NoteResp) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *NoteResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NoteResp) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

// 创建笔记请求
type CreateNoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteReq) Reset() {
	*x = CreateNoteReq{}
	mi := &file_SyncNote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteReq) ProtoMessage() {}

func (x *CreateNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_SyncNote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteReq.ProtoReflect.Descriptor instead.
func (*CreateNoteReq) Descriptor() ([]byte, []int) {
	return file_SyncNote_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNoteReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateNoteReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNoteReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateNoteReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// 笔记变更请求
type NoteChangeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SectionId     string                 `protobuf:"bytes,3,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Operations    []*EditOperation       `protobuf:"bytes,4,rep,name=operations,proto3" json:"operations,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteChangeReq) Reset() {
	*x = NoteChangeReq{}
	mi := &file_SyncNote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteChangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteChangeReq) ProtoMessage() {}

func (x *NoteChangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_SyncNote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteChangeReq.ProtoReflect.Descriptor instead.
func (*NoteChangeReq) Descriptor() ([]byte, []int) {
	return file_SyncNote_proto_rawDescGZIP(), []int{4}
}

func (x *NoteChangeReq) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *NoteChangeReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NoteChangeReq) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *NoteChangeReq) GetOperations() []*EditOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *NoteChangeReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 同步响应
type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MergedContent string                 `protobuf:"bytes,4,opt,name=merged_content,json=mergedContent,proto3" json:"merged_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_SyncNote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SyncNote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_SyncNote_proto_rawDescGZIP(), []int{5}
}

func (x *SyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SyncResponse) GetMergedContent() string {
	if x != nil {
		return x.MergedContent
	}
	return ""
}

// 获取用户笔记请求
type UserNotesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNotesReq) Reset() {
	*x = UserNotesReq{}
	mi := &file_SyncNote_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotesReq) ProtoMessage() {}

func (x *UserNotesReq) ProtoReflect() protoreflect.Message {
	mi := &file_SyncNote_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotesReq.ProtoReflect.Descriptor instead.
func (*UserNotesReq) Descriptor() ([]byte, []int) {
	return file_SyncNote_proto_rawDescGZIP(), []int{6}
}

func (x *UserNotesReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 获取用户笔记响应
type UserNotesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*NoteResp            `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNotesResp) Reset() {
	*x = UserNotesResp{}
	mi := &file_SyncNote_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotesResp) ProtoMessage() {}

func (x *UserNotesResp) ProtoReflect() protoreflect.Message {
	mi := &file_SyncNote_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotesResp.ProtoReflect.Descriptor instead.
func (*UserNotesResp) Descriptor() ([]byte, []int) {
	return file_SyncNote_proto_rawDescGZIP(), []int{7}
}

func (x *UserNotesResp) GetNotes() []*NoteResp {
	if x != nil {
		return x.Notes
	}
	return nil
}

var File_SyncNote_proto protoreflect.FileDescriptor

const file_SyncNote_proto_rawDesc = "" +
	"\n" +
	"\x0eSyncNote.proto\x12\vsyncnoterpc\"j\n" +
	"\rEditOperation\x12\x17\n" +
	"\aop_type\x18\x01 \x01(\tR\x06opType\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x05R\x03end\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"U\n" +
	"\aNoteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"\xc9\x01\n" +
	"\bNoteResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12#\n" +
	"\rlast_modified\x18\a \x01(\x03R\flastModified\"{\n" +
	"\rCreateNoteReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"\xba\x01\n" +
	"\rNoteChangeReq\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"section_id\x18\x03 \x01(\tR\tsectionId\x12:\n" +
	"\n" +
	"operations\x18\x04 \x03(\v2\x1a.syncnoterpc.EditOperationR\n" +
	"operations\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x87\x01\n" +
	"\fSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0emerged_content\x18\x04 \x01(\tR\rmergedContent\"'\n" +
	"\fUserNotesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"<\n" +
	"\rUserNotesResp\x12+\n" +
	"\x05notes\x18\x01 \x03(\v2\x15.syncnoterpc.NoteRespR\x05notes2\xcf\x02\n" +
	"\vSyncnoterpc\x12?\n" +
	"\n" +
	"CreateNote\x12\x1a.syncnoterpc.CreateNoteReq\x1a\x15.syncnoterpc.NoteResp\x126\n" +
	"\aGetNote\x12\x14.syncnoterpc.NoteReq\x1a\x15.syncnoterpc.NoteResp\x12G\n" +
	"\x0eSyncNoteChange\x12\x1a.syncnoterpc.NoteChangeReq\x1a\x19.syncnoterpc.SyncResponse\x127\n" +
	"\bSaveNote\x12\x14.syncnoterpc.NoteReq\x1a\x15.syncnoterpc.NoteResp\x12E\n" +
	"\fGetUserNotes\x12\x19.syncnoterpc.UserNotesReq\x1a\x1a.syncnoterpc.UserNotesRespB\x0fZ\r./syncnoterpcb\x06proto3"

var (
	file_SyncNote_proto_rawDescOnce sync.Once
	file_SyncNote_proto_rawDescData []byte
)

func file_SyncNote_proto_rawDescGZIP() []byte {
	file_SyncNote_proto_rawDescOnce.Do(func() {
		file_SyncNote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SyncNote_proto_rawDesc), len(file_SyncNote_proto_rawDesc)))
	})
	return file_SyncNote_proto_rawDescData
}

var file_SyncNote_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_SyncNote_proto_goTypes = []any{
	(*EditOperation)(nil), // 0: syncnoterpc.EditOperation
	(*NoteReq)(nil),       // 1: syncnoterpc.NoteReq
	(*NoteResp)(nil),      // 2: syncnoterpc.NoteResp
	(*CreateNoteReq)(nil), // 3: syncnoterpc.CreateNoteReq
	(*NoteChangeReq)(nil), // 4: syncnoterpc.NoteChangeReq
	(*SyncResponse)(nil),  // 5: syncnoterpc.SyncResponse
	(*UserNotesReq)(nil),  // 6: syncnoterpc.UserNotesReq
	(*UserNotesResp)(nil), // 7: syncnoterpc.UserNotesResp
}
var file_SyncNote_proto_depIdxs = []int32{
	0, // 0: syncnoterpc.NoteChangeReq.operations:type_name -> syncnoterpc.EditOperation
	2, // 1: syncnoterpc.UserNotesResp.notes:type_name -> syncnoterpc.NoteResp
	3, // 2: syncnoterpc.Syncnoterpc.CreateNote:input_type -> syncnoterpc.CreateNoteReq
	1, // 3: syncnoterpc.Syncnoterpc.GetNote:input_type -> syncnoterpc.NoteReq
	4, // 4: syncnoterpc.Syncnoterpc.SyncNoteChange:input_type -> syncnoterpc.NoteChangeReq
	1, // 5: syncnoterpc.Syncnoterpc.SaveNote:input_type -> syncnoterpc.NoteReq
	6, // 6: syncnoterpc.Syncnoterpc.GetUserNotes:input_type -> syncnoterpc.UserNotesReq
	2, // 7: syncnoterpc.Syncnoterpc.CreateNote:output_type -> syncnoterpc.NoteResp
	2, // 8: syncnoterpc.Syncnoterpc.GetNote:output_type -> syncnoterpc.NoteResp
	5, // 9: syncnoterpc.Syncnoterpc.SyncNoteChange:output_type -> syncnoterpc.SyncResponse
	2, // 10: syncnoterpc.Syncnoterpc.SaveNote:output_type -> syncnoterpc.NoteResp
	7, // 11: syncnoterpc.Syncnoterpc.GetUserNotes:output_type -> syncnoterpc.UserNotesResp
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_SyncNote_proto_init() }
func file_SyncNote_proto_init() {
	if File_SyncNote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SyncNote_proto_rawDesc), len(file_SyncNote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_SyncNote_proto_goTypes,
		DependencyIndexes: file_SyncNote_proto_depIdxs,
		MessageInfos:      file_SyncNote_proto_msgTypes,
	}.Build()
	File_SyncNote_proto = out.File
	file_SyncNote_proto_goTypes = nil
	file_SyncNote_proto_depIdxs = nil
}
