// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: SyncNote.proto

package syncnoterpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Syncnoterpc_CreateNote_FullMethodName     = "/syncnoterpc.Syncnoterpc/CreateNote"
	Syncnoterpc_GetNote_FullMethodName        = "/syncnoterpc.Syncnoterpc/GetNote"
	Syncnoterpc_SyncNoteChange_FullMethodName = "/syncnoterpc.Syncnoterpc/SyncNoteChange"
	Syncnoterpc_SaveNote_FullMethodName       = "/syncnoterpc.Syncnoterpc/SaveNote"
	Syncnoterpc_GetUserNotes_FullMethodName   = "/syncnoterpc.Syncnoterpc/GetUserNotes"
)

// SyncnoterpcClient is the client API for Syncnoterpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 服务定义
type SyncnoterpcClient interface {
	CreateNote(ctx context.Context, in *CreateNoteReq, opts ...grpc.CallOption) (*NoteResp, error)
	GetNote(ctx context.Context, in *NoteReq, opts ...grpc.CallOption) (*NoteResp, error)
	SyncNoteChange(ctx context.Context, in *NoteChangeReq, opts ...grpc.CallOption) (*SyncResponse, error)
	SaveNote(ctx context.Context, in *NoteReq, opts ...grpc.CallOption) (*NoteResp, error)
	GetUserNotes(ctx context.Context, in *UserNotesReq, opts ...grpc.CallOption) (*UserNotesResp, error)
}

type syncnoterpcClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncnoterpcClient(cc grpc.ClientConnInterface) SyncnoterpcClient {
	return &syncnoterpcClient{cc}
}

func (c *syncnoterpcClient) CreateNote(ctx context.Context, in *CreateNoteReq, opts ...grpc.CallOption) (*NoteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteResp)
	err := c.cc.Invoke(ctx, Syncnoterpc_CreateNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoterpcClient) GetNote(ctx context.Context, in *NoteReq, opts ...grpc.CallOption) (*NoteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteResp)
	err := c.cc.Invoke(ctx, Syncnoterpc_GetNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoterpcClient) SyncNoteChange(ctx context.Context, in *NoteChangeReq, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, Syncnoterpc_SyncNoteChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoterpcClient) SaveNote(ctx context.Context, in *NoteReq, opts ...grpc.CallOption) (*NoteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteResp)
	err := c.cc.Invoke(ctx, Syncnoterpc_SaveNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoterpcClient) GetUserNotes(ctx context.Context, in *UserNotesReq, opts ...grpc.CallOption) (*UserNotesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserNotesResp)
	err := c.cc.Invoke(ctx, Syncnoterpc_GetUserNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncnoterpcServer is the server API for Syncnoterpc service.
// All implementations must embed UnimplementedSyncnoterpcServer
// for forward compatibility.
//
// 服务定义
type SyncnoterpcServer interface {
	CreateNote(context.Context, *CreateNoteReq) (*NoteResp, error)
	GetNote(context.Context, *NoteReq) (*NoteResp, error)
	SyncNoteChange(context.Context, *NoteChangeReq) (*SyncResponse, error)
	SaveNote(context.Context, *NoteReq) (*NoteResp, error)
	GetUserNotes(context.Context, *UserNotesReq) (*UserNotesResp, error)
	mustEmbedUnimplementedSyncnoterpcServer()
}

// UnimplementedSyncnoterpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncnoterpcServer struct{}

func (UnimplementedSyncnoterpcServer) CreateNote(context.Context, *CreateNoteReq) (*NoteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNote not implemented")
}
func (UnimplementedSyncnoterpcServer) GetNote(context.Context, *NoteReq) (*NoteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNote not implemented")
}
func (UnimplementedSyncnoterpcServer) SyncNoteChange(context.Context, *NoteChangeReq) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncNoteChange not implemented")
}
func (UnimplementedSyncnoterpcServer) SaveNote(context.Context, *NoteReq) (*NoteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveNote not implemented")
}
func (UnimplementedSyncnoterpcServer) GetUserNotes(context.Context, *UserNotesReq) (*UserNotesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserNotes not implemented")
}
func (UnimplementedSyncnoterpcServer) mustEmbedUnimplementedSyncnoterpcServer() {}
func (UnimplementedSyncnoterpcServer) testEmbeddedByValue()                     {}

// UnsafeSyncnoterpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncnoterpcServer will
// result in compilation errors.
type UnsafeSyncnoterpcServer interface {
	mustEmbedUnimplementedSyncnoterpcServer()
}

func RegisterSyncnoterpcServer(s grpc.ServiceRegistrar, srv SyncnoterpcServer) {
	// If the following call panics, it indicates UnimplementedSyncnoterpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Syncnoterpc_ServiceDesc, srv)
}

func _Syncnoterpc_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoterpcServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Syncnoterpc_CreateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoterpcServer).CreateNote(ctx, req.(*CreateNoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Syncnoterpc_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoterpcServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Syncnoterpc_GetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoterpcServer).GetNote(ctx, req.(*NoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Syncnoterpc_SyncNoteChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteChangeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoterpcServer).SyncNoteChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Syncnoterpc_SyncNoteChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoterpcServer).SyncNoteChange(ctx, req.(*NoteChangeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Syncnoterpc_SaveNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoterpcServer).SaveNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Syncnoterpc_SaveNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoterpcServer).SaveNote(ctx, req.(*NoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Syncnoterpc_GetUserNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserNotesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoterpcServer).GetUserNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Syncnoterpc_GetUserNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoterpcServer).GetUserNotes(ctx, req.(*UserNotesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Syncnoterpc_ServiceDesc is the grpc.ServiceDesc for Syncnoterpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Syncnoterpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "syncnoterpc.Syncnoterpc",
	HandlerType: (*SyncnoterpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNote",
			Handler:    _Syncnoterpc_CreateNote_Handler,
		},
		{
			MethodName: "GetNote",
			Handler:    _Syncnoterpc_GetNote_Handler,
		},
		{
			MethodName: "SyncNoteChange",
			Handler:    _Syncnoterpc_SyncNoteChange_Handler,
		},
		{
			MethodName: "SaveNote",
			Handler:    _Syncnoterpc_SaveNote_Handler,
		},
		{
			MethodName: "GetUserNotes",
			Handler:    _Syncnoterpc_GetUserNotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "SyncNote.proto",
}
