// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type EditReq struct {
	Username  string `json:"username"`
	Synopsis  string `json:"synopsis"`
	AvatarUrl string `json:"avatarUrl"`
}

type EmptyResp struct {
}

type GetUserInfoReq struct {
	UserId string `path:"userid"`
}

type GetUserInfoResp struct {
	UserInfo
}

type SearchReq struct {
	Email string `json:"email" in:"query"`
}

type SearchResp struct {
	InfoList []UserInfo `json:"infoList"`
	Total    int64      `json:"total"`
}

type UserInfo struct {
	Username  string `json:"username"`
	UserId    string `json:"userId"`
	Email     string `json:"email"`
	Synopsis  string `json:"synopsis"`
	AvatarUrl string `json:"avatarUrl"`
}
