// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateNoteReq struct {
	UserId  string
	Title   string
	Content string `json:"content,optional"`
}

type NoteReq struct {
	NoteId string
}

type NoteResp struct {
	NoteId       string
	UserId       string
	Title        string
	Content      string
	Version      int64
	LastModified int64
}

type NoteSummary struct {
	NoteId       string
	Title        string
	Version      int64
	LastModified int64
}

type SaveNoteReq struct {
	NoteId          string
	UserId          string
	Content         string
	ExpectedVersion int64
}

type SaveNoteResp struct {
	Success       bool
	Code          string
	Message       string
	Note          *NoteResp `json:"note,optional"`
	LatestVersion int64     `json:"latestVersion,optional"`
	LatestContent string    `json:"latestContent,optional"`
}

type UserNotesReq struct {
	UserId string
}

type UserNotesResp struct {
	Notes []NoteSummary
}
