// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateNoteReq struct {
	User_id      string `json:"userId"`
	Title        string `json:"title"`
	Content      string `json:"content"`     // 初始内容
	Content_type string `json:"contentType"` // 默认"text"
}

type EditOperation struct {
	Op_type string `json:"opType"`  // "insert", "delete", "replace"
	Start   int32  `json:"start"`   // 操作起始位置
	End     int32  `json:"end"`     // 操作结束位置
	Content string `json:"content"` // 操作内容（文本或序列化数据）
}

type NoteChangeReq struct {
	Note_id    string          `json:"noteId"`
	User_id    string          `json:"userId"`
	Section_id string          `json:"sectionId,optional"` // 可选：用于多节笔记（如章节）
	Operations []EditOperation `json:"operations"`         // 编辑操作列表
	Timestamp  int64           `json:"timestamp"`          // 操作时间戳（用于冲突解决）
}

type NoteReq struct {
	Id           string `json:"id"`          // 笔记ID
	Content_type string `json:"contentType"` // 内容类型（"text", "graphic"等，预留扩展）
}

type NoteResp struct {
	Id            string `json:"id"`
	User_id       string `json:"userId"`
	Title         string `json:"title"`
	Content       string `json:"content"`      // 当前内容（文本或序列化内容）
	Content_type  string `json:"contentType"`  // 内容类型（"text", "graphic"等）
	Timestamp     int64  `json:"timestamp"`    // 创建时间戳
	Last_modified int64  `json:"lastModified"` // 最后修改时间戳
}

type SyncResponse struct {
	Success        bool   `json:"success"`
	Message        string `json:"message"`
	Timestamp      int64  `json:"timestamp"`              // 服务器时间戳
	Merged_content string `json:"mergedContent,optional"` // 合并后的内容（可选）
}

type UserNotesReq struct {
	User_id string `json:"userId"`
}

type UserNotesResp struct {
	Notes []NoteResp `json:"notes"`
}
