// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: syncnote.proto

package syncnoterpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 枚举定义 ============
type PermissionLevel int32

const (
	PermissionLevel_PERMISSION_LEVEL_UNSPECIFIED PermissionLevel = 0
	PermissionLevel_PERMISSION_LEVEL_READ        PermissionLevel = 1
	PermissionLevel_PERMISSION_LEVEL_WRITE       PermissionLevel = 2
	PermissionLevel_PERMISSION_LEVEL_ADMIN       PermissionLevel = 3
)

// Enum value maps for PermissionLevel.
var (
	PermissionLevel_name = map[int32]string{
		0: "PERMISSION_LEVEL_UNSPECIFIED",
		1: "PERMISSION_LEVEL_READ",
		2: "PERMISSION_LEVEL_WRITE",
		3: "PERMISSION_LEVEL_ADMIN",
	}
	PermissionLevel_value = map[string]int32{
		"PERMISSION_LEVEL_UNSPECIFIED": 0,
		"PERMISSION_LEVEL_READ":        1,
		"PERMISSION_LEVEL_WRITE":       2,
		"PERMISSION_LEVEL_ADMIN":       3,
	}
)

func (x PermissionLevel) Enum() *PermissionLevel {
	p := new(PermissionLevel)
	*p = x
	return p
}

func (x PermissionLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_syncnote_proto_enumTypes[0].Descriptor()
}

func (PermissionLevel) Type() protoreflect.EnumType {
	return &file_syncnote_proto_enumTypes[0]
}

func (x PermissionLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionLevel.Descriptor instead.
func (PermissionLevel) EnumDescriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{0}
}

// ============ 通用消息 ============
type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_syncnote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_syncnote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// ============ 核心消息 ============
type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_syncnote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{2}
}

func (x *Note) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *Note) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Note) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Note) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Note) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Note) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Note) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UserPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionId  string                 `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	NoteId        string                 `protobuf:"bytes,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Level         PermissionLevel        `protobuf:"varint,4,opt,name=level,proto3,enum=syncnoterpc.PermissionLevel" json:"level,omitempty"`
	GrantedBy     string                 `protobuf:"bytes,5,opt,name=granted_by,json=grantedBy,proto3" json:"granted_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPermission) Reset() {
	*x = UserPermission{}
	mi := &file_syncnote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPermission) ProtoMessage() {}

func (x *UserPermission) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPermission.ProtoReflect.Descriptor instead.
func (*UserPermission) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{3}
}

func (x *UserPermission) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *UserPermission) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *UserPermission) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserPermission) GetLevel() PermissionLevel {
	if x != nil {
		return x.Level
	}
	return PermissionLevel_PERMISSION_LEVEL_UNSPECIFIED
}

func (x *UserPermission) GetGrantedBy() string {
	if x != nil {
		return x.GrantedBy
	}
	return ""
}

func (x *UserPermission) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_syncnote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{4}
}

func (x *Team) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Team) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Team) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Team) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TeamMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamMember) Reset() {
	*x = TeamMember{}
	mi := &file_syncnote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMember) ProtoMessage() {}

func (x *TeamMember) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamMember.ProtoReflect.Descriptor instead.
func (*TeamMember) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{5}
}

func (x *TeamMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TeamMember) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TeamMember) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TeamMember) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

// ============ Note 服务请求/响应 ============
type CreateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteRequest) Reset() {
	*x = CreateNoteRequest{}
	mi := &file_syncnote_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteRequest) ProtoMessage() {}

func (x *CreateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteRequest.ProtoReflect.Descriptor instead.
func (*CreateNoteRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{6}
}

func (x *CreateNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNoteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          *Note                  `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteResponse) Reset() {
	*x = CreateNoteResponse{}
	mi := &file_syncnote_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteResponse) ProtoMessage() {}

func (x *CreateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteResponse.ProtoReflect.Descriptor instead.
func (*CreateNoteResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{7}
}

func (x *CreateNoteResponse) GetNote() *Note {
	if x != nil {
		return x.Note
	}
	return nil
}

type GetNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteRequest) Reset() {
	*x = GetNoteRequest{}
	mi := &file_syncnote_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteRequest) ProtoMessage() {}

func (x *GetNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteRequest.ProtoReflect.Descriptor instead.
func (*GetNoteRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{8}
}

func (x *GetNoteRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

type GetNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          *Note                  `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteResponse) Reset() {
	*x = GetNoteResponse{}
	mi := &file_syncnote_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteResponse) ProtoMessage() {}

func (x *GetNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteResponse.ProtoReflect.Descriptor instead.
func (*GetNoteResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{9}
}

func (x *GetNoteResponse) GetNote() *Note {
	if x != nil {
		return x.Note
	}
	return nil
}

type UpdateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"` // 乐观锁
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteRequest) Reset() {
	*x = UpdateNoteRequest{}
	mi := &file_syncnote_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteRequest) ProtoMessage() {}

func (x *UpdateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateNoteRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateNoteRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *UpdateNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateNoteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateNoteRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          *Note                  `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteResponse) Reset() {
	*x = UpdateNoteResponse{}
	mi := &file_syncnote_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteResponse) ProtoMessage() {}

func (x *UpdateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteResponse.ProtoReflect.Descriptor instead.
func (*UpdateNoteResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateNoteResponse) GetNote() *Note {
	if x != nil {
		return x.Note
	}
	return nil
}

type DeleteNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteRequest) Reset() {
	*x = DeleteNoteRequest{}
	mi := &file_syncnote_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteRequest) ProtoMessage() {}

func (x *DeleteNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteRequest.ProtoReflect.Descriptor instead.
func (*DeleteNoteRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteNoteRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

type DeleteNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteResponse) Reset() {
	*x = DeleteNoteResponse{}
	mi := &file_syncnote_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteResponse) ProtoMessage() {}

func (x *DeleteNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteResponse.ProtoReflect.Descriptor instead.
func (*DeleteNoteResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteNoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListNotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotesRequest) Reset() {
	*x = ListNotesRequest{}
	mi := &file_syncnote_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotesRequest) ProtoMessage() {}

func (x *ListNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotesRequest.ProtoReflect.Descriptor instead.
func (*ListNotesRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{14}
}

func (x *ListNotesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListNotesRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type ListNotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*Note                `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotesResponse) Reset() {
	*x = ListNotesResponse{}
	mi := &file_syncnote_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotesResponse) ProtoMessage() {}

func (x *ListNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotesResponse.ProtoReflect.Descriptor instead.
func (*ListNotesResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{15}
}

func (x *ListNotesResponse) GetNotes() []*Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *ListNotesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 权限相关
type GrantNotePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	TargetUserId  string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	Level         PermissionLevel        `protobuf:"varint,3,opt,name=level,proto3,enum=syncnoterpc.PermissionLevel" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantNotePermissionRequest) Reset() {
	*x = GrantNotePermissionRequest{}
	mi := &file_syncnote_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantNotePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantNotePermissionRequest) ProtoMessage() {}

func (x *GrantNotePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantNotePermissionRequest.ProtoReflect.Descriptor instead.
func (*GrantNotePermissionRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{16}
}

func (x *GrantNotePermissionRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *GrantNotePermissionRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *GrantNotePermissionRequest) GetLevel() PermissionLevel {
	if x != nil {
		return x.Level
	}
	return PermissionLevel_PERMISSION_LEVEL_UNSPECIFIED
}

type GrantNotePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *UserPermission        `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantNotePermissionResponse) Reset() {
	*x = GrantNotePermissionResponse{}
	mi := &file_syncnote_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantNotePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantNotePermissionResponse) ProtoMessage() {}

func (x *GrantNotePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantNotePermissionResponse.ProtoReflect.Descriptor instead.
func (*GrantNotePermissionResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{17}
}

func (x *GrantNotePermissionResponse) GetPermission() *UserPermission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type RevokeNotePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	TargetUserId  string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeNotePermissionRequest) Reset() {
	*x = RevokeNotePermissionRequest{}
	mi := &file_syncnote_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeNotePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeNotePermissionRequest) ProtoMessage() {}

func (x *RevokeNotePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeNotePermissionRequest.ProtoReflect.Descriptor instead.
func (*RevokeNotePermissionRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{18}
}

func (x *RevokeNotePermissionRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *RevokeNotePermissionRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type RevokeNotePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeNotePermissionResponse) Reset() {
	*x = RevokeNotePermissionResponse{}
	mi := &file_syncnote_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeNotePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeNotePermissionResponse) ProtoMessage() {}

func (x *RevokeNotePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeNotePermissionResponse.ProtoReflect.Descriptor instead.
func (*RevokeNotePermissionResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{19}
}

func (x *RevokeNotePermissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListNotePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotePermissionsRequest) Reset() {
	*x = ListNotePermissionsRequest{}
	mi := &file_syncnote_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotePermissionsRequest) ProtoMessage() {}

func (x *ListNotePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotePermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListNotePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{20}
}

func (x *ListNotePermissionsRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

type ListNotePermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*UserPermission      `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotePermissionsResponse) Reset() {
	*x = ListNotePermissionsResponse{}
	mi := &file_syncnote_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotePermissionsResponse) ProtoMessage() {}

func (x *ListNotePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotePermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListNotePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{21}
}

func (x *ListNotePermissionsResponse) GetPermissions() []*UserPermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// ============ Team 服务请求/响应 ============
type CreateTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	mi := &file_syncnote_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{22}
}

func (x *CreateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTeamRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamResponse) Reset() {
	*x = CreateTeamResponse{}
	mi := &file_syncnote_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamResponse) ProtoMessage() {}

func (x *CreateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{23}
}

func (x *CreateTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type GetTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamRequest) Reset() {
	*x = GetTeamRequest{}
	mi := &file_syncnote_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamRequest) ProtoMessage() {}

func (x *GetTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamRequest.ProtoReflect.Descriptor instead.
func (*GetTeamRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{24}
}

func (x *GetTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamResponse) Reset() {
	*x = GetTeamResponse{}
	mi := &file_syncnote_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamResponse) ProtoMessage() {}

func (x *GetTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamResponse.ProtoReflect.Descriptor instead.
func (*GetTeamResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{25}
}

func (x *GetTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type UpdateTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamRequest) Reset() {
	*x = UpdateTeamRequest{}
	mi := &file_syncnote_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamRequest) ProtoMessage() {}

func (x *UpdateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeamRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *UpdateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTeamRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamResponse) Reset() {
	*x = UpdateTeamResponse{}
	mi := &file_syncnote_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamResponse) ProtoMessage() {}

func (x *UpdateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamResponse.ProtoReflect.Descriptor instead.
func (*UpdateTeamResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type DeleteTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamRequest) Reset() {
	*x = DeleteTeamRequest{}
	mi := &file_syncnote_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamRequest) ProtoMessage() {}

func (x *DeleteTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type DeleteTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamResponse) Reset() {
	*x = DeleteTeamResponse{}
	mi := &file_syncnote_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamResponse) ProtoMessage() {}

func (x *DeleteTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeamResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteTeamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type JoinTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTeamRequest) Reset() {
	*x = JoinTeamRequest{}
	mi := &file_syncnote_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTeamRequest) ProtoMessage() {}

func (x *JoinTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTeamRequest.ProtoReflect.Descriptor instead.
func (*JoinTeamRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{30}
}

func (x *JoinTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type JoinTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTeamResponse) Reset() {
	*x = JoinTeamResponse{}
	mi := &file_syncnote_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTeamResponse) ProtoMessage() {}

func (x *JoinTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTeamResponse.ProtoReflect.Descriptor instead.
func (*JoinTeamResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{31}
}

func (x *JoinTeamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ExitTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitTeamRequest) Reset() {
	*x = ExitTeamRequest{}
	mi := &file_syncnote_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitTeamRequest) ProtoMessage() {}

func (x *ExitTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitTeamRequest.ProtoReflect.Descriptor instead.
func (*ExitTeamRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{32}
}

func (x *ExitTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type ExitTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitTeamResponse) Reset() {
	*x = ExitTeamResponse{}
	mi := &file_syncnote_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitTeamResponse) ProtoMessage() {}

func (x *ExitTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitTeamResponse.ProtoReflect.Descriptor instead.
func (*ExitTeamResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{33}
}

func (x *ExitTeamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListTeamMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamMembersRequest) Reset() {
	*x = ListTeamMembersRequest{}
	mi := &file_syncnote_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamMembersRequest) ProtoMessage() {}

func (x *ListTeamMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamMembersRequest.ProtoReflect.Descriptor instead.
func (*ListTeamMembersRequest) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{34}
}

func (x *ListTeamMembersRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListTeamMembersRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListTeamMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*TeamMember          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamMembersResponse) Reset() {
	*x = ListTeamMembersResponse{}
	mi := &file_syncnote_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamMembersResponse) ProtoMessage() {}

func (x *ListTeamMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncnote_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamMembersResponse.ProtoReflect.Descriptor instead.
func (*ListTeamMembersResponse) Descriptor() ([]byte, []int) {
	return file_syncnote_proto_rawDescGZIP(), []int{35}
}

func (x *ListTeamMembersResponse) GetMembers() []*TeamMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListTeamMembersResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_syncnote_proto protoreflect.FileDescriptor

const file_syncnote_proto_rawDesc = "" +
	"\n" +
	"\x0esyncnote.proto\x12\vsyncnoterpc\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"v\n" +
	"\x12PaginationResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\xfa\x01\n" +
	"\x04Note\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf5\x01\n" +
	"\x0eUserPermission\x12#\n" +
	"\rpermission_id\x18\x01 \x01(\tR\fpermissionId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\tR\x06noteId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x122\n" +
	"\x05level\x18\x04 \x01(\x0e2\x1c.syncnoterpc.PermissionLevelR\x05level\x12\x1d\n" +
	"\n" +
	"granted_by\x18\x05 \x01(\tR\tgrantedBy\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe6\x01\n" +
	"\x04Team\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa3\x01\n" +
	"\n" +
	"TeamMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x127\n" +
	"\tjoined_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"C\n" +
	"\x11CreateNoteRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\";\n" +
	"\x12CreateNoteResponse\x12%\n" +
	"\x04note\x18\x01 \x01(\v2\x11.syncnoterpc.NoteR\x04note\")\n" +
	"\x0eGetNoteRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\"8\n" +
	"\x0fGetNoteResponse\x12%\n" +
	"\x04note\x18\x01 \x01(\v2\x11.syncnoterpc.NoteR\x04note\"v\n" +
	"\x11UpdateNoteRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\";\n" +
	"\x12UpdateNoteResponse\x12%\n" +
	"\x04note\x18\x01 \x01(\v2\x11.syncnoterpc.NoteR\x04note\",\n" +
	"\x11DeleteNoteRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\".\n" +
	"\x12DeleteNoteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"m\n" +
	"\x10ListNotesRequest\x12>\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1e.syncnoterpc.PaginationRequestR\n" +
	"pagination\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"}\n" +
	"\x11ListNotesResponse\x12'\n" +
	"\x05notes\x18\x01 \x03(\v2\x11.syncnoterpc.NoteR\x05notes\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.syncnoterpc.PaginationResponseR\n" +
	"pagination\"\x8f\x01\n" +
	"\x1aGrantNotePermissionRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\x122\n" +
	"\x05level\x18\x03 \x01(\x0e2\x1c.syncnoterpc.PermissionLevelR\x05level\"Z\n" +
	"\x1bGrantNotePermissionResponse\x12;\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x1b.syncnoterpc.UserPermissionR\n" +
	"permission\"\\\n" +
	"\x1bRevokeNotePermissionRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\"8\n" +
	"\x1cRevokeNotePermissionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x1aListNotePermissionsRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\"\\\n" +
	"\x1bListNotePermissionsResponse\x12=\n" +
	"\vpermissions\x18\x01 \x03(\v2\x1b.syncnoterpc.UserPermissionR\vpermissions\"I\n" +
	"\x11CreateTeamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\";\n" +
	"\x12CreateTeamResponse\x12%\n" +
	"\x04team\x18\x01 \x01(\v2\x11.syncnoterpc.TeamR\x04team\")\n" +
	"\x0eGetTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"8\n" +
	"\x0fGetTeamResponse\x12%\n" +
	"\x04team\x18\x01 \x01(\v2\x11.syncnoterpc.TeamR\x04team\"b\n" +
	"\x11UpdateTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\";\n" +
	"\x12UpdateTeamResponse\x12%\n" +
	"\x04team\x18\x01 \x01(\v2\x11.syncnoterpc.TeamR\x04team\",\n" +
	"\x11DeleteTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\".\n" +
	"\x12DeleteTeamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x0fJoinTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\",\n" +
	"\x10JoinTeamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x0fExitTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\",\n" +
	"\x10ExitTeamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"q\n" +
	"\x16ListTeamMembersRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.syncnoterpc.PaginationRequestR\n" +
	"pagination\"\x8d\x01\n" +
	"\x17ListTeamMembersResponse\x121\n" +
	"\amembers\x18\x01 \x03(\v2\x17.syncnoterpc.TeamMemberR\amembers\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.syncnoterpc.PaginationResponseR\n" +
	"pagination*\x86\x01\n" +
	"\x0fPermissionLevel\x12 \n" +
	"\x1cPERMISSION_LEVEL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PERMISSION_LEVEL_READ\x10\x01\x12\x1a\n" +
	"\x16PERMISSION_LEVEL_WRITE\x10\x02\x12\x1a\n" +
	"\x16PERMISSION_LEVEL_ADMIN\x10\x032\xf0\t\n" +
	"\vNoteService\x12M\n" +
	"\n" +
	"CreateNote\x12\x1e.syncnoterpc.CreateNoteRequest\x1a\x1f.syncnoterpc.CreateNoteResponse\x12D\n" +
	"\aGetNote\x12\x1b.syncnoterpc.GetNoteRequest\x1a\x1c.syncnoterpc.GetNoteResponse\x12M\n" +
	"\n" +
	"UpdateNote\x12\x1e.syncnoterpc.UpdateNoteRequest\x1a\x1f.syncnoterpc.UpdateNoteResponse\x12M\n" +
	"\n" +
	"DeleteNote\x12\x1e.syncnoterpc.DeleteNoteRequest\x1a\x1f.syncnoterpc.DeleteNoteResponse\x12J\n" +
	"\tListNotes\x12\x1d.syncnoterpc.ListNotesRequest\x1a\x1e.syncnoterpc.ListNotesResponse\x12h\n" +
	"\x13GrantNotePermission\x12'.syncnoterpc.GrantNotePermissionRequest\x1a(.syncnoterpc.GrantNotePermissionResponse\x12k\n" +
	"\x14RevokeNotePermission\x12(.syncnoterpc.RevokeNotePermissionRequest\x1a).syncnoterpc.RevokeNotePermissionResponse\x12h\n" +
	"\x13ListNotePermissions\x12'.syncnoterpc.ListNotePermissionsRequest\x1a(.syncnoterpc.ListNotePermissionsResponse\x12M\n" +
	"\n" +
	"CreateTeam\x12\x1e.syncnoterpc.CreateTeamRequest\x1a\x1f.syncnoterpc.CreateTeamResponse\x12D\n" +
	"\aGetTeam\x12\x1b.syncnoterpc.GetTeamRequest\x1a\x1c.syncnoterpc.GetTeamResponse\x12M\n" +
	"\n" +
	"UpdateTeam\x12\x1e.syncnoterpc.UpdateTeamRequest\x1a\x1f.syncnoterpc.UpdateTeamResponse\x12M\n" +
	"\n" +
	"DeleteTeam\x12\x1e.syncnoterpc.DeleteTeamRequest\x1a\x1f.syncnoterpc.DeleteTeamResponse\x12G\n" +
	"\bJoinTeam\x12\x1c.syncnoterpc.JoinTeamRequest\x1a\x1d.syncnoterpc.JoinTeamResponse\x12G\n" +
	"\bExitTeam\x12\x1c.syncnoterpc.ExitTeamRequest\x1a\x1d.syncnoterpc.ExitTeamResponse\x12\\\n" +
	"\x0fListTeamMembers\x12#.syncnoterpc.ListTeamMembersRequest\x1a$.syncnoterpc.ListTeamMembersResponseB\x0fZ\r./syncnoterpcb\x06proto3"

var (
	file_syncnote_proto_rawDescOnce sync.Once
	file_syncnote_proto_rawDescData []byte
)

func file_syncnote_proto_rawDescGZIP() []byte {
	file_syncnote_proto_rawDescOnce.Do(func() {
		file_syncnote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_syncnote_proto_rawDesc), len(file_syncnote_proto_rawDesc)))
	})
	return file_syncnote_proto_rawDescData
}

var file_syncnote_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_syncnote_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_syncnote_proto_goTypes = []any{
	(PermissionLevel)(0),                 // 0: syncnoterpc.PermissionLevel
	(*PaginationRequest)(nil),            // 1: syncnoterpc.PaginationRequest
	(*PaginationResponse)(nil),           // 2: syncnoterpc.PaginationResponse
	(*Note)(nil),                         // 3: syncnoterpc.Note
	(*UserPermission)(nil),               // 4: syncnoterpc.UserPermission
	(*Team)(nil),                         // 5: syncnoterpc.Team
	(*TeamMember)(nil),                   // 6: syncnoterpc.TeamMember
	(*CreateNoteRequest)(nil),            // 7: syncnoterpc.CreateNoteRequest
	(*CreateNoteResponse)(nil),           // 8: syncnoterpc.CreateNoteResponse
	(*GetNoteRequest)(nil),               // 9: syncnoterpc.GetNoteRequest
	(*GetNoteResponse)(nil),              // 10: syncnoterpc.GetNoteResponse
	(*UpdateNoteRequest)(nil),            // 11: syncnoterpc.UpdateNoteRequest
	(*UpdateNoteResponse)(nil),           // 12: syncnoterpc.UpdateNoteResponse
	(*DeleteNoteRequest)(nil),            // 13: syncnoterpc.DeleteNoteRequest
	(*DeleteNoteResponse)(nil),           // 14: syncnoterpc.DeleteNoteResponse
	(*ListNotesRequest)(nil),             // 15: syncnoterpc.ListNotesRequest
	(*ListNotesResponse)(nil),            // 16: syncnoterpc.ListNotesResponse
	(*GrantNotePermissionRequest)(nil),   // 17: syncnoterpc.GrantNotePermissionRequest
	(*GrantNotePermissionResponse)(nil),  // 18: syncnoterpc.GrantNotePermissionResponse
	(*RevokeNotePermissionRequest)(nil),  // 19: syncnoterpc.RevokeNotePermissionRequest
	(*RevokeNotePermissionResponse)(nil), // 20: syncnoterpc.RevokeNotePermissionResponse
	(*ListNotePermissionsRequest)(nil),   // 21: syncnoterpc.ListNotePermissionsRequest
	(*ListNotePermissionsResponse)(nil),  // 22: syncnoterpc.ListNotePermissionsResponse
	(*CreateTeamRequest)(nil),            // 23: syncnoterpc.CreateTeamRequest
	(*CreateTeamResponse)(nil),           // 24: syncnoterpc.CreateTeamResponse
	(*GetTeamRequest)(nil),               // 25: syncnoterpc.GetTeamRequest
	(*GetTeamResponse)(nil),              // 26: syncnoterpc.GetTeamResponse
	(*UpdateTeamRequest)(nil),            // 27: syncnoterpc.UpdateTeamRequest
	(*UpdateTeamResponse)(nil),           // 28: syncnoterpc.UpdateTeamResponse
	(*DeleteTeamRequest)(nil),            // 29: syncnoterpc.DeleteTeamRequest
	(*DeleteTeamResponse)(nil),           // 30: syncnoterpc.DeleteTeamResponse
	(*JoinTeamRequest)(nil),              // 31: syncnoterpc.JoinTeamRequest
	(*JoinTeamResponse)(nil),             // 32: syncnoterpc.JoinTeamResponse
	(*ExitTeamRequest)(nil),              // 33: syncnoterpc.ExitTeamRequest
	(*ExitTeamResponse)(nil),             // 34: syncnoterpc.ExitTeamResponse
	(*ListTeamMembersRequest)(nil),       // 35: syncnoterpc.ListTeamMembersRequest
	(*ListTeamMembersResponse)(nil),      // 36: syncnoterpc.ListTeamMembersResponse
	(*timestamppb.Timestamp)(nil),        // 37: google.protobuf.Timestamp
}
var file_syncnote_proto_depIdxs = []int32{
	37, // 0: syncnoterpc.Note.created_at:type_name -> google.protobuf.Timestamp
	37, // 1: syncnoterpc.Note.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: syncnoterpc.UserPermission.level:type_name -> syncnoterpc.PermissionLevel
	37, // 3: syncnoterpc.UserPermission.created_at:type_name -> google.protobuf.Timestamp
	37, // 4: syncnoterpc.Team.created_at:type_name -> google.protobuf.Timestamp
	37, // 5: syncnoterpc.Team.updated_at:type_name -> google.protobuf.Timestamp
	37, // 6: syncnoterpc.TeamMember.joined_at:type_name -> google.protobuf.Timestamp
	3,  // 7: syncnoterpc.CreateNoteResponse.note:type_name -> syncnoterpc.Note
	3,  // 8: syncnoterpc.GetNoteResponse.note:type_name -> syncnoterpc.Note
	3,  // 9: syncnoterpc.UpdateNoteResponse.note:type_name -> syncnoterpc.Note
	1,  // 10: syncnoterpc.ListNotesRequest.pagination:type_name -> syncnoterpc.PaginationRequest
	3,  // 11: syncnoterpc.ListNotesResponse.notes:type_name -> syncnoterpc.Note
	2,  // 12: syncnoterpc.ListNotesResponse.pagination:type_name -> syncnoterpc.PaginationResponse
	0,  // 13: syncnoterpc.GrantNotePermissionRequest.level:type_name -> syncnoterpc.PermissionLevel
	4,  // 14: syncnoterpc.GrantNotePermissionResponse.permission:type_name -> syncnoterpc.UserPermission
	4,  // 15: syncnoterpc.ListNotePermissionsResponse.permissions:type_name -> syncnoterpc.UserPermission
	5,  // 16: syncnoterpc.CreateTeamResponse.team:type_name -> syncnoterpc.Team
	5,  // 17: syncnoterpc.GetTeamResponse.team:type_name -> syncnoterpc.Team
	5,  // 18: syncnoterpc.UpdateTeamResponse.team:type_name -> syncnoterpc.Team
	1,  // 19: syncnoterpc.ListTeamMembersRequest.pagination:type_name -> syncnoterpc.PaginationRequest
	6,  // 20: syncnoterpc.ListTeamMembersResponse.members:type_name -> syncnoterpc.TeamMember
	2,  // 21: syncnoterpc.ListTeamMembersResponse.pagination:type_name -> syncnoterpc.PaginationResponse
	7,  // 22: syncnoterpc.NoteService.CreateNote:input_type -> syncnoterpc.CreateNoteRequest
	9,  // 23: syncnoterpc.NoteService.GetNote:input_type -> syncnoterpc.GetNoteRequest
	11, // 24: syncnoterpc.NoteService.UpdateNote:input_type -> syncnoterpc.UpdateNoteRequest
	13, // 25: syncnoterpc.NoteService.DeleteNote:input_type -> syncnoterpc.DeleteNoteRequest
	15, // 26: syncnoterpc.NoteService.ListNotes:input_type -> syncnoterpc.ListNotesRequest
	17, // 27: syncnoterpc.NoteService.GrantNotePermission:input_type -> syncnoterpc.GrantNotePermissionRequest
	19, // 28: syncnoterpc.NoteService.RevokeNotePermission:input_type -> syncnoterpc.RevokeNotePermissionRequest
	21, // 29: syncnoterpc.NoteService.ListNotePermissions:input_type -> syncnoterpc.ListNotePermissionsRequest
	23, // 30: syncnoterpc.NoteService.CreateTeam:input_type -> syncnoterpc.CreateTeamRequest
	25, // 31: syncnoterpc.NoteService.GetTeam:input_type -> syncnoterpc.GetTeamRequest
	27, // 32: syncnoterpc.NoteService.UpdateTeam:input_type -> syncnoterpc.UpdateTeamRequest
	29, // 33: syncnoterpc.NoteService.DeleteTeam:input_type -> syncnoterpc.DeleteTeamRequest
	31, // 34: syncnoterpc.NoteService.JoinTeam:input_type -> syncnoterpc.JoinTeamRequest
	33, // 35: syncnoterpc.NoteService.ExitTeam:input_type -> syncnoterpc.ExitTeamRequest
	35, // 36: syncnoterpc.NoteService.ListTeamMembers:input_type -> syncnoterpc.ListTeamMembersRequest
	8,  // 37: syncnoterpc.NoteService.CreateNote:output_type -> syncnoterpc.CreateNoteResponse
	10, // 38: syncnoterpc.NoteService.GetNote:output_type -> syncnoterpc.GetNoteResponse
	12, // 39: syncnoterpc.NoteService.UpdateNote:output_type -> syncnoterpc.UpdateNoteResponse
	14, // 40: syncnoterpc.NoteService.DeleteNote:output_type -> syncnoterpc.DeleteNoteResponse
	16, // 41: syncnoterpc.NoteService.ListNotes:output_type -> syncnoterpc.ListNotesResponse
	18, // 42: syncnoterpc.NoteService.GrantNotePermission:output_type -> syncnoterpc.GrantNotePermissionResponse
	20, // 43: syncnoterpc.NoteService.RevokeNotePermission:output_type -> syncnoterpc.RevokeNotePermissionResponse
	22, // 44: syncnoterpc.NoteService.ListNotePermissions:output_type -> syncnoterpc.ListNotePermissionsResponse
	24, // 45: syncnoterpc.NoteService.CreateTeam:output_type -> syncnoterpc.CreateTeamResponse
	26, // 46: syncnoterpc.NoteService.GetTeam:output_type -> syncnoterpc.GetTeamResponse
	28, // 47: syncnoterpc.NoteService.UpdateTeam:output_type -> syncnoterpc.UpdateTeamResponse
	30, // 48: syncnoterpc.NoteService.DeleteTeam:output_type -> syncnoterpc.DeleteTeamResponse
	32, // 49: syncnoterpc.NoteService.JoinTeam:output_type -> syncnoterpc.JoinTeamResponse
	34, // 50: syncnoterpc.NoteService.ExitTeam:output_type -> syncnoterpc.ExitTeamResponse
	36, // 51: syncnoterpc.NoteService.ListTeamMembers:output_type -> syncnoterpc.ListTeamMembersResponse
	37, // [37:52] is the sub-list for method output_type
	22, // [22:37] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_syncnote_proto_init() }
func file_syncnote_proto_init() {
	if File_syncnote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_syncnote_proto_rawDesc), len(file_syncnote_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_syncnote_proto_goTypes,
		DependencyIndexes: file_syncnote_proto_depIdxs,
		EnumInfos:         file_syncnote_proto_enumTypes,
		MessageInfos:      file_syncnote_proto_msgTypes,
	}.Build()
	File_syncnote_proto = out.File
	file_syncnote_proto_goTypes = nil
	file_syncnote_proto_depIdxs = nil
}
