// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	collaborationEventsFieldNames          = builder.RawFieldNames(&CollaborationEvents{})
	collaborationEventsRows                = strings.Join(collaborationEventsFieldNames, ",")
	collaborationEventsRowsExpectAutoSet   = strings.Join(stringx.Remove(collaborationEventsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	collaborationEventsRowsWithPlaceHolder = strings.Join(stringx.Remove(collaborationEventsFieldNames, "`event_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCollaborationEventsEventIdPrefix        = "cache:collaborationEvents:eventId:"
	cacheCollaborationEventsNoteIdEventSeqPrefix = "cache:collaborationEvents:noteId:eventSeq:"
)

type (
	collaborationEventsModel interface {
		Insert(ctx context.Context, data *CollaborationEvents) (sql.Result, error)
		FindOne(ctx context.Context, eventId string) (*CollaborationEvents, error)
		FindOneByNoteIdEventSeq(ctx context.Context, noteId string, eventSeq int64) (*CollaborationEvents, error)
		Update(ctx context.Context, data *CollaborationEvents) error
		Delete(ctx context.Context, eventId string) error
	}

	defaultCollaborationEventsModel struct {
		sqlc.CachedConn
		table string
	}

	CollaborationEvents struct {
		EventId         string         `db:"event_id"`         // 事件唯一ID
		NoteId          string         `db:"note_id"`          // 操作的笔记ID
		EventSeq        int64          `db:"event_seq"`        // 该笔记内事件序列号（单调递增）
		EventType       string         `db:"event_type"`       // 事件类型
		OperatorId      string         `db:"operator_id"`      // 操作者用户ID
		OperatorName    sql.NullString `db:"operator_name"`    // 操作者用户名（冗余字段）
		Payload         sql.NullString `db:"payload"`          // 事件具体内容
		NoteVersion     sql.NullInt64  `db:"note_version"`     // 操作后笔记版本号
		ExpectedVersion sql.NullInt64  `db:"expected_version"` // 预期版本号（用于冲突检测）
		IsConflict      int64          `db:"is_conflict"`      // 是否冲突：0否 1是
		RelatedEventId  sql.NullString `db:"related_event_id"` // 关联冲突事件ID
		CreatedAt       int64          `db:"created_at"`       // 事件发生时间戳(ms)
	}
)

func newCollaborationEventsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCollaborationEventsModel {
	return &defaultCollaborationEventsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`collaboration_events`",
	}
}

func (m *defaultCollaborationEventsModel) Delete(ctx context.Context, eventId string) error {
	data, err := m.FindOne(ctx, eventId)
	if err != nil {
		return err
	}

	collaborationEventsEventIdKey := fmt.Sprintf("%s%v", cacheCollaborationEventsEventIdPrefix, eventId)
	collaborationEventsNoteIdEventSeqKey := fmt.Sprintf("%s%v:%v", cacheCollaborationEventsNoteIdEventSeqPrefix, data.NoteId, data.EventSeq)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `event_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, eventId)
	}, collaborationEventsEventIdKey, collaborationEventsNoteIdEventSeqKey)
	return err
}

func (m *defaultCollaborationEventsModel) FindOne(ctx context.Context, eventId string) (*CollaborationEvents, error) {
	collaborationEventsEventIdKey := fmt.Sprintf("%s%v", cacheCollaborationEventsEventIdPrefix, eventId)
	var resp CollaborationEvents
	err := m.QueryRowCtx(ctx, &resp, collaborationEventsEventIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `event_id` = ? limit 1", collaborationEventsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, eventId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollaborationEventsModel) FindOneByNoteIdEventSeq(ctx context.Context, noteId string, eventSeq int64) (*CollaborationEvents, error) {
	collaborationEventsNoteIdEventSeqKey := fmt.Sprintf("%s%v:%v", cacheCollaborationEventsNoteIdEventSeqPrefix, noteId, eventSeq)
	var resp CollaborationEvents
	err := m.QueryRowIndexCtx(ctx, &resp, collaborationEventsNoteIdEventSeqKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `note_id` = ? and `event_seq` = ? limit 1", collaborationEventsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, noteId, eventSeq); err != nil {
			return nil, err
		}
		return resp.EventId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollaborationEventsModel) Insert(ctx context.Context, data *CollaborationEvents) (sql.Result, error) {
	collaborationEventsEventIdKey := fmt.Sprintf("%s%v", cacheCollaborationEventsEventIdPrefix, data.EventId)
	collaborationEventsNoteIdEventSeqKey := fmt.Sprintf("%s%v:%v", cacheCollaborationEventsNoteIdEventSeqPrefix, data.NoteId, data.EventSeq)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, collaborationEventsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.EventId, data.NoteId, data.EventSeq, data.EventType, data.OperatorId, data.OperatorName, data.Payload, data.NoteVersion, data.ExpectedVersion, data.IsConflict, data.RelatedEventId)
	}, collaborationEventsEventIdKey, collaborationEventsNoteIdEventSeqKey)
	return ret, err
}

func (m *defaultCollaborationEventsModel) Update(ctx context.Context, newData *CollaborationEvents) error {
	data, err := m.FindOne(ctx, newData.EventId)
	if err != nil {
		return err
	}

	collaborationEventsEventIdKey := fmt.Sprintf("%s%v", cacheCollaborationEventsEventIdPrefix, data.EventId)
	collaborationEventsNoteIdEventSeqKey := fmt.Sprintf("%s%v:%v", cacheCollaborationEventsNoteIdEventSeqPrefix, data.NoteId, data.EventSeq)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `event_id` = ?", m.table, collaborationEventsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.NoteId, newData.EventSeq, newData.EventType, newData.OperatorId, newData.OperatorName, newData.Payload, newData.NoteVersion, newData.ExpectedVersion, newData.IsConflict, newData.RelatedEventId, newData.EventId)
	}, collaborationEventsEventIdKey, collaborationEventsNoteIdEventSeqKey)
	return err
}

func (m *defaultCollaborationEventsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCollaborationEventsEventIdPrefix, primary)
}

func (m *defaultCollaborationEventsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `event_id` = ? limit 1", collaborationEventsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCollaborationEventsModel) tableName() string {
	return m.table
}
