// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	notePermissionsFieldNames          = builder.RawFieldNames(&NotePermissions{})
	notePermissionsRows                = strings.Join(notePermissionsFieldNames, ",")
	notePermissionsRowsExpectAutoSet   = strings.Join(stringx.Remove(notePermissionsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	notePermissionsRowsWithPlaceHolder = strings.Join(stringx.Remove(notePermissionsFieldNames, "`permission_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheNotePermissionsPermissionIdPrefix = "cache:notePermissions:permissionId:"
	cacheNotePermissionsNoteIdTeamIdPrefix = "cache:notePermissions:noteId:teamId:"
	cacheNotePermissionsNoteIdUserIdPrefix = "cache:notePermissions:noteId:userId:"
)

type (
	notePermissionsModel interface {
		Insert(ctx context.Context, data *NotePermissions) (sql.Result, error)
		FindOne(ctx context.Context, permissionId string) (*NotePermissions, error)
		FindOneByNoteIdTeamId(ctx context.Context, noteId string, teamId sql.NullString) (*NotePermissions, error)
		FindOneByNoteIdUserId(ctx context.Context, noteId string, userId sql.NullString) (*NotePermissions, error)
		Update(ctx context.Context, data *NotePermissions) error
		Delete(ctx context.Context, permissionId string) error
	}

	defaultNotePermissionsModel struct {
		sqlc.CachedConn
		table string
	}

	NotePermissions struct {
		PermissionId string         `db:"permission_id"` // 权限记录唯一ID
		NoteId       string         `db:"note_id"`       // 笔记ID
		UserId       sql.NullString `db:"user_id"`       // 被授权用户ID，user_id 和 team_id 二选一
		TeamId       sql.NullString `db:"team_id"`       // 被授权团队ID（团队成员自动继承权限）
		GrantedBy    string         `db:"granted_by"`    // 授权者ID（note owner or admin）
		Role         string         `db:"role"`          // 权限角色：owner | admin | editor | viewer
		Status       string         `db:"status"`        // active | revoked | pending
		GrantedAt    int64          `db:"granted_at"`    // 授权时间戳(ms)
		RevokedAt    sql.NullInt64  `db:"revoked_at"`    // 撤销时间戳(ms)
	}
)

func newNotePermissionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultNotePermissionsModel {
	return &defaultNotePermissionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`note_permissions`",
	}
}

func (m *defaultNotePermissionsModel) Delete(ctx context.Context, permissionId string) error {
	data, err := m.FindOne(ctx, permissionId)
	if err != nil {
		return err
	}

	notePermissionsNoteIdTeamIdKey := fmt.Sprintf("%s%v:%v", cacheNotePermissionsNoteIdTeamIdPrefix, data.NoteId, data.TeamId)
	notePermissionsNoteIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheNotePermissionsNoteIdUserIdPrefix, data.NoteId, data.UserId)
	notePermissionsPermissionIdKey := fmt.Sprintf("%s%v", cacheNotePermissionsPermissionIdPrefix, permissionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `permission_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, permissionId)
	}, notePermissionsNoteIdTeamIdKey, notePermissionsNoteIdUserIdKey, notePermissionsPermissionIdKey)
	return err
}

func (m *defaultNotePermissionsModel) FindOne(ctx context.Context, permissionId string) (*NotePermissions, error) {
	notePermissionsPermissionIdKey := fmt.Sprintf("%s%v", cacheNotePermissionsPermissionIdPrefix, permissionId)
	var resp NotePermissions
	err := m.QueryRowCtx(ctx, &resp, notePermissionsPermissionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `permission_id` = ? limit 1", notePermissionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, permissionId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNotePermissionsModel) FindOneByNoteIdTeamId(ctx context.Context, noteId string, teamId sql.NullString) (*NotePermissions, error) {
	notePermissionsNoteIdTeamIdKey := fmt.Sprintf("%s%v:%v", cacheNotePermissionsNoteIdTeamIdPrefix, noteId, teamId)
	var resp NotePermissions
	err := m.QueryRowIndexCtx(ctx, &resp, notePermissionsNoteIdTeamIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `note_id` = ? and `team_id` = ? limit 1", notePermissionsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, noteId, teamId); err != nil {
			return nil, err
		}
		return resp.PermissionId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNotePermissionsModel) FindOneByNoteIdUserId(ctx context.Context, noteId string, userId sql.NullString) (*NotePermissions, error) {
	notePermissionsNoteIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheNotePermissionsNoteIdUserIdPrefix, noteId, userId)
	var resp NotePermissions
	err := m.QueryRowIndexCtx(ctx, &resp, notePermissionsNoteIdUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `note_id` = ? and `user_id` = ? limit 1", notePermissionsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, noteId, userId); err != nil {
			return nil, err
		}
		return resp.PermissionId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNotePermissionsModel) Insert(ctx context.Context, data *NotePermissions) (sql.Result, error) {
	notePermissionsNoteIdTeamIdKey := fmt.Sprintf("%s%v:%v", cacheNotePermissionsNoteIdTeamIdPrefix, data.NoteId, data.TeamId)
	notePermissionsNoteIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheNotePermissionsNoteIdUserIdPrefix, data.NoteId, data.UserId)
	notePermissionsPermissionIdKey := fmt.Sprintf("%s%v", cacheNotePermissionsPermissionIdPrefix, data.PermissionId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, notePermissionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PermissionId, data.NoteId, data.UserId, data.TeamId, data.GrantedBy, data.Role, data.Status, data.GrantedAt, data.RevokedAt)
	}, notePermissionsNoteIdTeamIdKey, notePermissionsNoteIdUserIdKey, notePermissionsPermissionIdKey)
	return ret, err
}

func (m *defaultNotePermissionsModel) Update(ctx context.Context, newData *NotePermissions) error {
	data, err := m.FindOne(ctx, newData.PermissionId)
	if err != nil {
		return err
	}

	notePermissionsNoteIdTeamIdKey := fmt.Sprintf("%s%v:%v", cacheNotePermissionsNoteIdTeamIdPrefix, data.NoteId, data.TeamId)
	notePermissionsNoteIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheNotePermissionsNoteIdUserIdPrefix, data.NoteId, data.UserId)
	notePermissionsPermissionIdKey := fmt.Sprintf("%s%v", cacheNotePermissionsPermissionIdPrefix, data.PermissionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `permission_id` = ?", m.table, notePermissionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.NoteId, newData.UserId, newData.TeamId, newData.GrantedBy, newData.Role, newData.Status, newData.GrantedAt, newData.RevokedAt, newData.PermissionId)
	}, notePermissionsNoteIdTeamIdKey, notePermissionsNoteIdUserIdKey, notePermissionsPermissionIdKey)
	return err
}

func (m *defaultNotePermissionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheNotePermissionsPermissionIdPrefix, primary)
}

func (m *defaultNotePermissionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `permission_id` = ? limit 1", notePermissionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultNotePermissionsModel) tableName() string {
	return m.table
}
