// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: syncnote.proto

package noteservice

import (
	"context"

	"SyncNote/rebuild/syncnote/rpc/internal/rpc/syncnoterpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateNoteRequest            = syncnoterpc.CreateNoteRequest
	CreateNoteResponse           = syncnoterpc.CreateNoteResponse
	CreateTeamRequest            = syncnoterpc.CreateTeamRequest
	CreateTeamResponse           = syncnoterpc.CreateTeamResponse
	DeleteNoteRequest            = syncnoterpc.DeleteNoteRequest
	DeleteNoteResponse           = syncnoterpc.DeleteNoteResponse
	DeleteTeamRequest            = syncnoterpc.DeleteTeamRequest
	DeleteTeamResponse           = syncnoterpc.DeleteTeamResponse
	ExitTeamRequest              = syncnoterpc.ExitTeamRequest
	ExitTeamResponse             = syncnoterpc.ExitTeamResponse
	GetNoteRequest               = syncnoterpc.GetNoteRequest
	GetNoteResponse              = syncnoterpc.GetNoteResponse
	GetTeamRequest               = syncnoterpc.GetTeamRequest
	GetTeamResponse              = syncnoterpc.GetTeamResponse
	GrantNotePermissionRequest   = syncnoterpc.GrantNotePermissionRequest
	GrantNotePermissionResponse  = syncnoterpc.GrantNotePermissionResponse
	JoinTeamRequest              = syncnoterpc.JoinTeamRequest
	JoinTeamResponse             = syncnoterpc.JoinTeamResponse
	ListNotePermissionsRequest   = syncnoterpc.ListNotePermissionsRequest
	ListNotePermissionsResponse  = syncnoterpc.ListNotePermissionsResponse
	ListNotesRequest             = syncnoterpc.ListNotesRequest
	ListNotesResponse            = syncnoterpc.ListNotesResponse
	ListTeamMembersRequest       = syncnoterpc.ListTeamMembersRequest
	ListTeamMembersResponse      = syncnoterpc.ListTeamMembersResponse
	Note                         = syncnoterpc.Note
	PaginationRequest            = syncnoterpc.PaginationRequest
	PaginationResponse           = syncnoterpc.PaginationResponse
	RevokeNotePermissionRequest  = syncnoterpc.RevokeNotePermissionRequest
	RevokeNotePermissionResponse = syncnoterpc.RevokeNotePermissionResponse
	Team                         = syncnoterpc.Team
	TeamMember                   = syncnoterpc.TeamMember
	UpdateNoteRequest            = syncnoterpc.UpdateNoteRequest
	UpdateNoteResponse           = syncnoterpc.UpdateNoteResponse
	UpdateTeamRequest            = syncnoterpc.UpdateTeamRequest
	UpdateTeamResponse           = syncnoterpc.UpdateTeamResponse
	UserPermission               = syncnoterpc.UserPermission

	NoteService interface {
		CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error)
		GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error)
		UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...grpc.CallOption) (*UpdateNoteResponse, error)
		DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error)
		ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error)
		GrantNotePermission(ctx context.Context, in *GrantNotePermissionRequest, opts ...grpc.CallOption) (*GrantNotePermissionResponse, error)
		RevokeNotePermission(ctx context.Context, in *RevokeNotePermissionRequest, opts ...grpc.CallOption) (*RevokeNotePermissionResponse, error)
		ListNotePermissions(ctx context.Context, in *ListNotePermissionsRequest, opts ...grpc.CallOption) (*ListNotePermissionsResponse, error)
		CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error)
		GetTeam(ctx context.Context, in *GetTeamRequest, opts ...grpc.CallOption) (*GetTeamResponse, error)
		UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*UpdateTeamResponse, error)
		DeleteTeam(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*DeleteTeamResponse, error)
		JoinTeam(ctx context.Context, in *JoinTeamRequest, opts ...grpc.CallOption) (*JoinTeamResponse, error)
		ExitTeam(ctx context.Context, in *ExitTeamRequest, opts ...grpc.CallOption) (*ExitTeamResponse, error)
		ListTeamMembers(ctx context.Context, in *ListTeamMembersRequest, opts ...grpc.CallOption) (*ListTeamMembersResponse, error)
	}

	defaultNoteService struct {
		cli zrpc.Client
	}
)

func NewNoteService(cli zrpc.Client) NoteService {
	return &defaultNoteService{
		cli: cli,
	}
}

func (m *defaultNoteService) CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.CreateNote(ctx, in, opts...)
}

func (m *defaultNoteService) GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.GetNote(ctx, in, opts...)
}

func (m *defaultNoteService) UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...grpc.CallOption) (*UpdateNoteResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.UpdateNote(ctx, in, opts...)
}

func (m *defaultNoteService) DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.DeleteNote(ctx, in, opts...)
}

func (m *defaultNoteService) ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.ListNotes(ctx, in, opts...)
}

func (m *defaultNoteService) GrantNotePermission(ctx context.Context, in *GrantNotePermissionRequest, opts ...grpc.CallOption) (*GrantNotePermissionResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.GrantNotePermission(ctx, in, opts...)
}

func (m *defaultNoteService) RevokeNotePermission(ctx context.Context, in *RevokeNotePermissionRequest, opts ...grpc.CallOption) (*RevokeNotePermissionResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.RevokeNotePermission(ctx, in, opts...)
}

func (m *defaultNoteService) ListNotePermissions(ctx context.Context, in *ListNotePermissionsRequest, opts ...grpc.CallOption) (*ListNotePermissionsResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.ListNotePermissions(ctx, in, opts...)
}

func (m *defaultNoteService) CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.CreateTeam(ctx, in, opts...)
}

func (m *defaultNoteService) GetTeam(ctx context.Context, in *GetTeamRequest, opts ...grpc.CallOption) (*GetTeamResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.GetTeam(ctx, in, opts...)
}

func (m *defaultNoteService) UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*UpdateTeamResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.UpdateTeam(ctx, in, opts...)
}

func (m *defaultNoteService) DeleteTeam(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*DeleteTeamResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.DeleteTeam(ctx, in, opts...)
}

func (m *defaultNoteService) JoinTeam(ctx context.Context, in *JoinTeamRequest, opts ...grpc.CallOption) (*JoinTeamResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.JoinTeam(ctx, in, opts...)
}

func (m *defaultNoteService) ExitTeam(ctx context.Context, in *ExitTeamRequest, opts ...grpc.CallOption) (*ExitTeamResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.ExitTeam(ctx, in, opts...)
}

func (m *defaultNoteService) ListTeamMembers(ctx context.Context, in *ListTeamMembersRequest, opts ...grpc.CallOption) (*ListTeamMembersResponse, error) {
	client := syncnoterpc.NewNoteServiceClient(m.cli.Conn())
	return client.ListTeamMembers(ctx, in, opts...)
}
