// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	LoginId  string `json:"loginId"`
	Password string `json:"password"`
}

type LoginResp struct {
	Code   int64  `json:"code"`
	UserId string `json:"userId"`
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Captcha  string `json:"captcha"`
	Password string `json:"password"`
	Username string `json:"username,optional"`
}

type RegisterResp struct {
	Code   int64  `json:"code"`
	UserId string `json:"userId"`
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}
