// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	noteTeamPermissionFieldNames          = builder.RawFieldNames(&NoteTeamPermission{})
	noteTeamPermissionRows                = strings.Join(noteTeamPermissionFieldNames, ",")
	noteTeamPermissionRowsExpectAutoSet   = strings.Join(stringx.Remove(noteTeamPermissionFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	noteTeamPermissionRowsWithPlaceHolder = strings.Join(stringx.Remove(noteTeamPermissionFieldNames, "`permission_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	noteTeamPermissionModel interface {
		Insert(ctx context.Context, data *NoteTeamPermission) (sql.Result, error)
		FindOne(ctx context.Context, permissionId string) (*NoteTeamPermission, error)
		FindOneByNoteIdTeamId(ctx context.Context, noteId string, teamId string) (*NoteTeamPermission, error)
		Update(ctx context.Context, data *NoteTeamPermission) error
		Delete(ctx context.Context, permissionId string) error
	}

	defaultNoteTeamPermissionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	NoteTeamPermission struct {
		PermissionId    string         `db:"permission_id"`
		NoteId          string         `db:"note_id"`          // 笔记ID
		TeamId          string         `db:"team_id"`          // 团队ID
		PermissionLevel string         `db:"permission_level"` // 权限级别 (read/write/admin)
		GrantedBy       sql.NullString `db:"granted_by"`       // 授权人ID (允许NULL用于SET NULL)
		CreatedAt       time.Time      `db:"created_at"`       // 创建时间
		UpdatedAt       time.Time      `db:"updated_at"`       // 更新时间
	}
)

func newNoteTeamPermissionModel(conn sqlx.SqlConn) *defaultNoteTeamPermissionModel {
	return &defaultNoteTeamPermissionModel{
		conn:  conn,
		table: "`note_team_permission`",
	}
}

func (m *defaultNoteTeamPermissionModel) Delete(ctx context.Context, permissionId string) error {
	query := fmt.Sprintf("delete from %s where `permission_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, permissionId)
	return err
}

func (m *defaultNoteTeamPermissionModel) FindOne(ctx context.Context, permissionId string) (*NoteTeamPermission, error) {
	query := fmt.Sprintf("select %s from %s where `permission_id` = ? limit 1", noteTeamPermissionRows, m.table)
	var resp NoteTeamPermission
	err := m.conn.QueryRowCtx(ctx, &resp, query, permissionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNoteTeamPermissionModel) FindOneByNoteIdTeamId(ctx context.Context, noteId string, teamId string) (*NoteTeamPermission, error) {
	var resp NoteTeamPermission
	query := fmt.Sprintf("select %s from %s where `note_id` = ? and `team_id` = ? limit 1", noteTeamPermissionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, noteId, teamId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNoteTeamPermissionModel) Insert(ctx context.Context, data *NoteTeamPermission) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, noteTeamPermissionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PermissionId, data.NoteId, data.TeamId, data.PermissionLevel, data.GrantedBy)
	return ret, err
}

func (m *defaultNoteTeamPermissionModel) Update(ctx context.Context, newData *NoteTeamPermission) error {
	query := fmt.Sprintf("update %s set %s where `permission_id` = ?", m.table, noteTeamPermissionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.NoteId, newData.TeamId, newData.PermissionLevel, newData.GrantedBy, newData.PermissionId)
	return err
}

func (m *defaultNoteTeamPermissionModel) tableName() string {
	return m.table
}
