// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	noteFieldNames          = builder.RawFieldNames(&Note{})
	noteRows                = strings.Join(noteFieldNames, ",")
	noteRowsExpectAutoSet   = strings.Join(stringx.Remove(noteFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	noteRowsWithPlaceHolder = strings.Join(stringx.Remove(noteFieldNames, "`note_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	noteModel interface {
		Insert(ctx context.Context, data *Note) (sql.Result, error)
		FindOne(ctx context.Context, noteId string) (*Note, error)
		Update(ctx context.Context, data *Note) error
		Delete(ctx context.Context, noteId string) error
	}

	defaultNoteModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Note struct {
		NoteId    string         `db:"note_id"`    // 笔记ID (UUID)
		OwnerId   string         `db:"owner_id"`   // 笔记所有者ID
		Title     string         `db:"title"`      // 笔记标题
		Content   sql.NullString `db:"content"`    // 笔记内容
		Version   int64          `db:"version"`    // 版本号 (乐观锁)
		CreatedAt time.Time      `db:"created_at"` // 创建时间
		UpdatedAt time.Time      `db:"updated_at"` // 更新时间
		DeletedAt sql.NullTime   `db:"deleted_at"` // 软删除时间
	}
)

func newNoteModel(conn sqlx.SqlConn) *defaultNoteModel {
	return &defaultNoteModel{
		conn:  conn,
		table: "`note`",
	}
}

func (m *defaultNoteModel) Delete(ctx context.Context, noteId string) error {
	query := fmt.Sprintf("delete from %s where `note_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, noteId)
	return err
}

func (m *defaultNoteModel) FindOne(ctx context.Context, noteId string) (*Note, error) {
	query := fmt.Sprintf("select %s from %s where `note_id` = ? limit 1", noteRows, m.table)
	var resp Note
	err := m.conn.QueryRowCtx(ctx, &resp, query, noteId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNoteModel) Insert(ctx context.Context, data *Note) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, noteRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.NoteId, data.OwnerId, data.Title, data.Content, data.Version, data.DeletedAt)
	return ret, err
}

func (m *defaultNoteModel) Update(ctx context.Context, data *Note) error {
	query := fmt.Sprintf("update %s set %s where `note_id` = ?", m.table, noteRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OwnerId, data.Title, data.Content, data.Version, data.DeletedAt, data.NoteId)
	return err
}

func (m *defaultNoteModel) tableName() string {
	return m.table
}
