// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	noteUserPermissionFieldNames          = builder.RawFieldNames(&NoteUserPermission{})
	noteUserPermissionRows                = strings.Join(noteUserPermissionFieldNames, ",")
	noteUserPermissionRowsExpectAutoSet   = strings.Join(stringx.Remove(noteUserPermissionFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	noteUserPermissionRowsWithPlaceHolder = strings.Join(stringx.Remove(noteUserPermissionFieldNames, "`permission_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	noteUserPermissionModel interface {
		Insert(ctx context.Context, data *NoteUserPermission) (sql.Result, error)
		FindOne(ctx context.Context, permissionId string) (*NoteUserPermission, error)
		FindOneByNoteIdUserId(ctx context.Context, noteId string, userId string) (*NoteUserPermission, error)
		Update(ctx context.Context, data *NoteUserPermission) error
		Delete(ctx context.Context, permissionId string) error
	}

	defaultNoteUserPermissionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	NoteUserPermission struct {
		PermissionId    string         `db:"permission_id"`
		NoteId          string         `db:"note_id"`          // 笔记ID
		UserId          string         `db:"user_id"`          // 用户ID
		PermissionLevel string         `db:"permission_level"` // 权限级别 (read/write/admin)
		GrantedBy       sql.NullString `db:"granted_by"`       // 授权人ID (允许NULL用于SET NULL)
		CreatedAt       time.Time      `db:"created_at"`       // 创建时间
		UpdatedAt       time.Time      `db:"updated_at"`       // 更新时间
	}
)

func newNoteUserPermissionModel(conn sqlx.SqlConn) *defaultNoteUserPermissionModel {
	return &defaultNoteUserPermissionModel{
		conn:  conn,
		table: "`note_user_permission`",
	}
}

func (m *defaultNoteUserPermissionModel) Delete(ctx context.Context, permissionId string) error {
	query := fmt.Sprintf("delete from %s where `permission_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, permissionId)
	return err
}

func (m *defaultNoteUserPermissionModel) FindOne(ctx context.Context, permissionId string) (*NoteUserPermission, error) {
	query := fmt.Sprintf("select %s from %s where `permission_id` = ? limit 1", noteUserPermissionRows, m.table)
	var resp NoteUserPermission
	err := m.conn.QueryRowCtx(ctx, &resp, query, permissionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNoteUserPermissionModel) FindOneByNoteIdUserId(ctx context.Context, noteId string, userId string) (*NoteUserPermission, error) {
	var resp NoteUserPermission
	query := fmt.Sprintf("select %s from %s where `note_id` = ? and `user_id` = ? limit 1", noteUserPermissionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, noteId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNoteUserPermissionModel) Insert(ctx context.Context, data *NoteUserPermission) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, noteUserPermissionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PermissionId, data.NoteId, data.UserId, data.PermissionLevel, data.GrantedBy)
	return ret, err
}

func (m *defaultNoteUserPermissionModel) Update(ctx context.Context, newData *NoteUserPermission) error {
	query := fmt.Sprintf("update %s set %s where `permission_id` = ?", m.table, noteUserPermissionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.NoteId, newData.UserId, newData.PermissionLevel, newData.GrantedBy, newData.PermissionId)
	return err
}

func (m *defaultNoteUserPermissionModel) tableName() string {
	return m.table
}
