// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	teamFieldNames          = builder.RawFieldNames(&Team{})
	teamRows                = strings.Join(teamFieldNames, ",")
	teamRowsExpectAutoSet   = strings.Join(stringx.Remove(teamFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	teamRowsWithPlaceHolder = strings.Join(stringx.Remove(teamFieldNames, "`team_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	teamModel interface {
		Insert(ctx context.Context, data *Team) (sql.Result, error)
		FindOne(ctx context.Context, teamId string) (*Team, error)
		Update(ctx context.Context, data *Team) error
		Delete(ctx context.Context, teamId string) error
	}

	defaultTeamModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Team struct {
		TeamId      string         `db:"team_id"`     // 团队ID (UUID)
		Name        string         `db:"name"`        // 团队名称
		Description sql.NullString `db:"description"` // 团队描述
		OwnerId     string         `db:"owner_id"`    // 团队所有者ID
		CreatedAt   time.Time      `db:"created_at"`  // 创建时间
		UpdatedAt   time.Time      `db:"updated_at"`  // 更新时间
		DeletedAt   sql.NullTime   `db:"deleted_at"`  // 软删除时间
	}
)

func newTeamModel(conn sqlx.SqlConn) *defaultTeamModel {
	return &defaultTeamModel{
		conn:  conn,
		table: "`team`",
	}
}

func (m *defaultTeamModel) Delete(ctx context.Context, teamId string) error {
	query := fmt.Sprintf("delete from %s where `team_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, teamId)
	return err
}

func (m *defaultTeamModel) FindOne(ctx context.Context, teamId string) (*Team, error) {
	query := fmt.Sprintf("select %s from %s where `team_id` = ? limit 1", teamRows, m.table)
	var resp Team
	err := m.conn.QueryRowCtx(ctx, &resp, query, teamId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTeamModel) Insert(ctx context.Context, data *Team) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, teamRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TeamId, data.Name, data.Description, data.OwnerId, data.DeletedAt)
	return ret, err
}

func (m *defaultTeamModel) Update(ctx context.Context, data *Team) error {
	query := fmt.Sprintf("update %s set %s where `team_id` = ?", m.table, teamRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.OwnerId, data.DeletedAt, data.TeamId)
	return err
}

func (m *defaultTeamModel) tableName() string {
	return m.table
}
