// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	teamMembersFieldNames          = builder.RawFieldNames(&TeamMembers{})
	teamMembersRows                = strings.Join(teamMembersFieldNames, ",")
	teamMembersRowsExpectAutoSet   = strings.Join(stringx.Remove(teamMembersFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	teamMembersRowsWithPlaceHolder = strings.Join(stringx.Remove(teamMembersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	teamMembersModel interface {
		Insert(ctx context.Context, data *TeamMembers) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*TeamMembers, error)
		FindOneByTeamIdUserId(ctx context.Context, teamId string, userId string) (*TeamMembers, error)
		Update(ctx context.Context, data *TeamMembers) error
		Delete(ctx context.Context, id string) error
	}

	defaultTeamMembersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TeamMembers struct {
		Id       string    `db:"id"`
		TeamId   string    `db:"team_id"`   // 团队ID
		UserId   string    `db:"user_id"`   // 用户ID
		JoinedAt time.Time `db:"joined_at"` // 加入时间
	}
)

func newTeamMembersModel(conn sqlx.SqlConn) *defaultTeamMembersModel {
	return &defaultTeamMembersModel{
		conn:  conn,
		table: "`team_members`",
	}
}

func (m *defaultTeamMembersModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTeamMembersModel) FindOne(ctx context.Context, id string) (*TeamMembers, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", teamMembersRows, m.table)
	var resp TeamMembers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTeamMembersModel) FindOneByTeamIdUserId(ctx context.Context, teamId string, userId string) (*TeamMembers, error) {
	var resp TeamMembers
	query := fmt.Sprintf("select %s from %s where `team_id` = ? and `user_id` = ? limit 1", teamMembersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, teamId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTeamMembersModel) Insert(ctx context.Context, data *TeamMembers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, teamMembersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.TeamId, data.UserId, data.JoinedAt)
	return ret, err
}

func (m *defaultTeamMembersModel) Update(ctx context.Context, newData *TeamMembers) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, teamMembersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TeamId, newData.UserId, newData.JoinedAt, newData.Id)
	return err
}

func (m *defaultTeamMembersModel) tableName() string {
	return m.table
}
