// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: syncNoterpc.proto

package syncnoterpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveCode int32

const (
	SaveCode_SAVE_CODE_UNSPECIFIED      SaveCode = 0
	SaveCode_SAVE_CODE_OK               SaveCode = 1
	SaveCode_SAVE_CODE_VERSION_CONFLICT SaveCode = 2
	SaveCode_SAVE_CODE_NOT_FOUND        SaveCode = 3
	SaveCode_SAVE_CODE_INVALID_PARAM    SaveCode = 4
)

// Enum value maps for SaveCode.
var (
	SaveCode_name = map[int32]string{
		0: "SAVE_CODE_UNSPECIFIED",
		1: "SAVE_CODE_OK",
		2: "SAVE_CODE_VERSION_CONFLICT",
		3: "SAVE_CODE_NOT_FOUND",
		4: "SAVE_CODE_INVALID_PARAM",
	}
	SaveCode_value = map[string]int32{
		"SAVE_CODE_UNSPECIFIED":      0,
		"SAVE_CODE_OK":               1,
		"SAVE_CODE_VERSION_CONFLICT": 2,
		"SAVE_CODE_NOT_FOUND":        3,
		"SAVE_CODE_INVALID_PARAM":    4,
	}
)

func (x SaveCode) Enum() *SaveCode {
	p := new(SaveCode)
	*p = x
	return p
}

func (x SaveCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SaveCode) Descriptor() protoreflect.EnumDescriptor {
	return file_syncNoterpc_proto_enumTypes[0].Descriptor()
}

func (SaveCode) Type() protoreflect.EnumType {
	return &file_syncNoterpc_proto_enumTypes[0]
}

func (x SaveCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SaveCode.Descriptor instead.
func (SaveCode) EnumDescriptor() ([]byte, []int) {
	return file_syncNoterpc_proto_rawDescGZIP(), []int{0}
}

type CreateNoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteReq) Reset() {
	*x = CreateNoteReq{}
	mi := &file_syncNoterpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteReq) ProtoMessage() {}

func (x *CreateNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_syncNoterpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteReq.ProtoReflect.Descriptor instead.
func (*CreateNoteReq) Descriptor() ([]byte, []int) {
	return file_syncNoterpc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNoteReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateNoteReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNoteReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type NoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteReq) Reset() {
	*x = NoteReq{}
	mi := &file_syncNoterpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteReq) ProtoMessage() {}

func (x *NoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_syncNoterpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteReq.ProtoReflect.Descriptor instead.
func (*NoteReq) Descriptor() ([]byte, []int) {
	return file_syncNoterpc_proto_rawDescGZIP(), []int{1}
}

func (x *NoteReq) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

type SaveNoteReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NoteId          string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	Title           string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SaveNoteReq) Reset() {
	*x = SaveNoteReq{}
	mi := &file_syncNoterpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveNoteReq) ProtoMessage() {}

func (x *SaveNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_syncNoterpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveNoteReq.ProtoReflect.Descriptor instead.
func (*SaveNoteReq) Descriptor() ([]byte, []int) {
	return file_syncNoterpc_proto_rawDescGZIP(), []int{2}
}

func (x *SaveNoteReq) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *SaveNoteReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveNoteReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SaveNoteReq) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *SaveNoteReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type NoteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	LastModified  int64                  `protobuf:"varint,6,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteResp) Reset() {
	*x = NoteResp{}
	mi := &file_syncNoterpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteResp) ProtoMessage() {}

func (x *NoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_syncNoterpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteResp.ProtoReflect.Descriptor instead.
func (*NoteResp) Descriptor() ([]byte, []int) {
	return file_syncNoterpc_proto_rawDescGZIP(), []int{3}
}

func (x *NoteResp) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *NoteResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NoteResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NoteResp) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NoteResp) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

type NoteSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	LastModified  int64                  `protobuf:"varint,4,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteSummary) Reset() {
	*x = NoteSummary{}
	mi := &file_syncNoterpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteSummary) ProtoMessage() {}

func (x *NoteSummary) ProtoReflect() protoreflect.Message {
	mi := &file_syncNoterpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteSummary.ProtoReflect.Descriptor instead.
func (*NoteSummary) Descriptor() ([]byte, []int) {
	return file_syncNoterpc_proto_rawDescGZIP(), []int{4}
}

func (x *NoteSummary) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *NoteSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteSummary) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NoteSummary) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

type UserNotesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNotesReq) Reset() {
	*x = UserNotesReq{}
	mi := &file_syncNoterpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotesReq) ProtoMessage() {}

func (x *UserNotesReq) ProtoReflect() protoreflect.Message {
	mi := &file_syncNoterpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotesReq.ProtoReflect.Descriptor instead.
func (*UserNotesReq) Descriptor() ([]byte, []int) {
	return file_syncNoterpc_proto_rawDescGZIP(), []int{5}
}

func (x *UserNotesReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserNotesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*NoteSummary         `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNotesResp) Reset() {
	*x = UserNotesResp{}
	mi := &file_syncNoterpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotesResp) ProtoMessage() {}

func (x *UserNotesResp) ProtoReflect() protoreflect.Message {
	mi := &file_syncNoterpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotesResp.ProtoReflect.Descriptor instead.
func (*UserNotesResp) Descriptor() ([]byte, []int) {
	return file_syncNoterpc_proto_rawDescGZIP(), []int{6}
}

func (x *UserNotesResp) GetNotes() []*NoteSummary {
	if x != nil {
		return x.Notes
	}
	return nil
}

type SaveNoteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          SaveCode               `protobuf:"varint,2,opt,name=code,proto3,enum=syncnoterpc.SaveCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Note          *NoteResp              `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	LatestVersion int64                  `protobuf:"varint,5,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveNoteResp) Reset() {
	*x = SaveNoteResp{}
	mi := &file_syncNoterpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveNoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveNoteResp) ProtoMessage() {}

func (x *SaveNoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_syncNoterpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveNoteResp.ProtoReflect.Descriptor instead.
func (*SaveNoteResp) Descriptor() ([]byte, []int) {
	return file_syncNoterpc_proto_rawDescGZIP(), []int{7}
}

func (x *SaveNoteResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveNoteResp) GetCode() SaveCode {
	if x != nil {
		return x.Code
	}
	return SaveCode_SAVE_CODE_UNSPECIFIED
}

func (x *SaveNoteResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SaveNoteResp) GetNote() *NoteResp {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *SaveNoteResp) GetLatestVersion() int64 {
	if x != nil {
		return x.LatestVersion
	}
	return 0
}

var File_syncNoterpc_proto protoreflect.FileDescriptor

const file_syncNoterpc_proto_rawDesc = "" +
	"\n" +
	"\x11syncNoterpc.proto\x12\vsyncnoterpc\"X\n" +
	"\rCreateNoteReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\"\n" +
	"\aNoteReq\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\"\x9a\x01\n" +
	"\vSaveNoteReq\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x03R\x0fexpectedVersion\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\"\xab\x01\n" +
	"\bNoteResp\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12#\n" +
	"\rlast_modified\x18\x06 \x01(\x03R\flastModified\"{\n" +
	"\vNoteSummary\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12#\n" +
	"\rlast_modified\x18\x04 \x01(\x03R\flastModified\"'\n" +
	"\fUserNotesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"?\n" +
	"\rUserNotesResp\x12.\n" +
	"\x05notes\x18\x01 \x03(\v2\x18.syncnoterpc.NoteSummaryR\x05notes\"\xbf\x01\n" +
	"\fSaveNoteResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x04code\x18\x02 \x01(\x0e2\x15.syncnoterpc.SaveCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12)\n" +
	"\x04note\x18\x04 \x01(\v2\x15.syncnoterpc.NoteRespR\x04note\x12%\n" +
	"\x0elatest_version\x18\x05 \x01(\x03R\rlatestVersion*\x8d\x01\n" +
	"\bSaveCode\x12\x19\n" +
	"\x15SAVE_CODE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSAVE_CODE_OK\x10\x01\x12\x1e\n" +
	"\x1aSAVE_CODE_VERSION_CONFLICT\x10\x02\x12\x17\n" +
	"\x13SAVE_CODE_NOT_FOUND\x10\x03\x12\x1b\n" +
	"\x17SAVE_CODE_INVALID_PARAM\x10\x042\x8e\x02\n" +
	"\vSyncnoterpc\x12?\n" +
	"\n" +
	"CreateNote\x12\x1a.syncnoterpc.CreateNoteReq\x1a\x15.syncnoterpc.NoteResp\x126\n" +
	"\aGetNote\x12\x14.syncnoterpc.NoteReq\x1a\x15.syncnoterpc.NoteResp\x12?\n" +
	"\bSaveNote\x12\x18.syncnoterpc.SaveNoteReq\x1a\x19.syncnoterpc.SaveNoteResp\x12E\n" +
	"\fGetUserNotes\x12\x19.syncnoterpc.UserNotesReq\x1a\x1a.syncnoterpc.UserNotesRespB\x0fZ\r./syncnoterpcb\x06proto3"

var (
	file_syncNoterpc_proto_rawDescOnce sync.Once
	file_syncNoterpc_proto_rawDescData []byte
)

func file_syncNoterpc_proto_rawDescGZIP() []byte {
	file_syncNoterpc_proto_rawDescOnce.Do(func() {
		file_syncNoterpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_syncNoterpc_proto_rawDesc), len(file_syncNoterpc_proto_rawDesc)))
	})
	return file_syncNoterpc_proto_rawDescData
}

var file_syncNoterpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_syncNoterpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_syncNoterpc_proto_goTypes = []any{
	(SaveCode)(0),         // 0: syncnoterpc.SaveCode
	(*CreateNoteReq)(nil), // 1: syncnoterpc.CreateNoteReq
	(*NoteReq)(nil),       // 2: syncnoterpc.NoteReq
	(*SaveNoteReq)(nil),   // 3: syncnoterpc.SaveNoteReq
	(*NoteResp)(nil),      // 4: syncnoterpc.NoteResp
	(*NoteSummary)(nil),   // 5: syncnoterpc.NoteSummary
	(*UserNotesReq)(nil),  // 6: syncnoterpc.UserNotesReq
	(*UserNotesResp)(nil), // 7: syncnoterpc.UserNotesResp
	(*SaveNoteResp)(nil),  // 8: syncnoterpc.SaveNoteResp
}
var file_syncNoterpc_proto_depIdxs = []int32{
	5, // 0: syncnoterpc.UserNotesResp.notes:type_name -> syncnoterpc.NoteSummary
	0, // 1: syncnoterpc.SaveNoteResp.code:type_name -> syncnoterpc.SaveCode
	4, // 2: syncnoterpc.SaveNoteResp.note:type_name -> syncnoterpc.NoteResp
	1, // 3: syncnoterpc.Syncnoterpc.CreateNote:input_type -> syncnoterpc.CreateNoteReq
	2, // 4: syncnoterpc.Syncnoterpc.GetNote:input_type -> syncnoterpc.NoteReq
	3, // 5: syncnoterpc.Syncnoterpc.SaveNote:input_type -> syncnoterpc.SaveNoteReq
	6, // 6: syncnoterpc.Syncnoterpc.GetUserNotes:input_type -> syncnoterpc.UserNotesReq
	4, // 7: syncnoterpc.Syncnoterpc.CreateNote:output_type -> syncnoterpc.NoteResp
	4, // 8: syncnoterpc.Syncnoterpc.GetNote:output_type -> syncnoterpc.NoteResp
	8, // 9: syncnoterpc.Syncnoterpc.SaveNote:output_type -> syncnoterpc.SaveNoteResp
	7, // 10: syncnoterpc.Syncnoterpc.GetUserNotes:output_type -> syncnoterpc.UserNotesResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_syncNoterpc_proto_init() }
func file_syncNoterpc_proto_init() {
	if File_syncNoterpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_syncNoterpc_proto_rawDesc), len(file_syncNoterpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_syncNoterpc_proto_goTypes,
		DependencyIndexes: file_syncNoterpc_proto_depIdxs,
		EnumInfos:         file_syncNoterpc_proto_enumTypes,
		MessageInfos:      file_syncNoterpc_proto_msgTypes,
	}.Build()
	File_syncNoterpc_proto = out.File
	file_syncNoterpc_proto_goTypes = nil
	file_syncNoterpc_proto_depIdxs = nil
}
