// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: syncnote.proto

package server

import (
	"context"

	"SyncNote/rebuild/syncnote/rpc/internal/logic"
	"SyncNote/rebuild/syncnote/rpc/internal/svc"
	"SyncNote/rebuild/syncnote/rpc/pb/syncnoterpc"
)

type SyncnoteServiceServer struct {
	svcCtx *svc.ServiceContext
	syncnoterpc.UnimplementedSyncnoteServiceServer
}

func NewSyncnoteServiceServer(svcCtx *svc.ServiceContext) *SyncnoteServiceServer {
	return &SyncnoteServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SyncnoteServiceServer) CreateNote(ctx context.Context, in *syncnoterpc.CreateNoteRequest) (*syncnoterpc.CreateNoteResponse, error) {
	l := logic.NewCreateNoteLogic(ctx, s.svcCtx)
	return l.CreateNote(in)
}

func (s *SyncnoteServiceServer) GetNote(ctx context.Context, in *syncnoterpc.GetNoteRequest) (*syncnoterpc.GetNoteResponse, error) {
	l := logic.NewGetNoteLogic(ctx, s.svcCtx)
	return l.GetNote(in)
}

func (s *SyncnoteServiceServer) UpdateNote(ctx context.Context, in *syncnoterpc.UpdateNoteRequest) (*syncnoterpc.UpdateNoteResponse, error) {
	l := logic.NewUpdateNoteLogic(ctx, s.svcCtx)
	return l.UpdateNote(in)
}

func (s *SyncnoteServiceServer) DeleteNote(ctx context.Context, in *syncnoterpc.DeleteNoteRequest) (*syncnoterpc.DeleteNoteResponse, error) {
	l := logic.NewDeleteNoteLogic(ctx, s.svcCtx)
	return l.DeleteNote(in)
}

func (s *SyncnoteServiceServer) GrantNotePermission(ctx context.Context, in *syncnoterpc.GrantNotePermissionRequest) (*syncnoterpc.GrantNotePermissionResponse, error) {
	l := logic.NewGrantNotePermissionLogic(ctx, s.svcCtx)
	return l.GrantNotePermission(in)
}

func (s *SyncnoteServiceServer) RevokeNotePermission(ctx context.Context, in *syncnoterpc.RevokeNotePermissionRequest) (*syncnoterpc.RevokeNotePermissionResponse, error) {
	l := logic.NewRevokeNotePermissionLogic(ctx, s.svcCtx)
	return l.RevokeNotePermission(in)
}

func (s *SyncnoteServiceServer) CreateTeam(ctx context.Context, in *syncnoterpc.CreateTeamRequest) (*syncnoterpc.CreateTeamResponse, error) {
	l := logic.NewCreateTeamLogic(ctx, s.svcCtx)
	return l.CreateTeam(in)
}

func (s *SyncnoteServiceServer) GetTeam(ctx context.Context, in *syncnoterpc.GetTeamRequest) (*syncnoterpc.GetTeamResponse, error) {
	l := logic.NewGetTeamLogic(ctx, s.svcCtx)
	return l.GetTeam(in)
}

func (s *SyncnoteServiceServer) UpdateTeam(ctx context.Context, in *syncnoterpc.UpdateTeamRequest) (*syncnoterpc.UpdateTeamResponse, error) {
	l := logic.NewUpdateTeamLogic(ctx, s.svcCtx)
	return l.UpdateTeam(in)
}

func (s *SyncnoteServiceServer) DeleteTeam(ctx context.Context, in *syncnoterpc.DeleteTeamRequest) (*syncnoterpc.DeleteTeamResponse, error) {
	l := logic.NewDeleteTeamLogic(ctx, s.svcCtx)
	return l.DeleteTeam(in)
}

func (s *SyncnoteServiceServer) JoinTeam(ctx context.Context, in *syncnoterpc.JoinTeamRequest) (*syncnoterpc.JoinTeamResponse, error) {
	l := logic.NewJoinTeamLogic(ctx, s.svcCtx)
	return l.JoinTeam(in)
}

func (s *SyncnoteServiceServer) ExitTeam(ctx context.Context, in *syncnoterpc.ExitTeamRequest) (*syncnoterpc.ExitTeamResponse, error) {
	l := logic.NewExitTeamLogic(ctx, s.svcCtx)
	return l.ExitTeam(in)
}
