// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type LoginReq struct {
	Email    string `json:"email"`
	Captcha  string `json:"captcha"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string `json:"token"`
	ExpireIn int64  `json:"expirein"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Captcha  string `json:"captcha"`
	Password string `json:"password"`
}

type RegisterResp struct {
	UserId string `json:"userId"`
}
