// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: syncnote.proto

package syncnoterpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncnoteService_CreateNote_FullMethodName           = "/syncnoterpc.SyncnoteService/CreateNote"
	SyncnoteService_GetNote_FullMethodName              = "/syncnoterpc.SyncnoteService/GetNote"
	SyncnoteService_UpdateNote_FullMethodName           = "/syncnoterpc.SyncnoteService/UpdateNote"
	SyncnoteService_DeleteNote_FullMethodName           = "/syncnoterpc.SyncnoteService/DeleteNote"
	SyncnoteService_GrantNotePermission_FullMethodName  = "/syncnoterpc.SyncnoteService/GrantNotePermission"
	SyncnoteService_RevokeNotePermission_FullMethodName = "/syncnoterpc.SyncnoteService/RevokeNotePermission"
	SyncnoteService_CreateTeam_FullMethodName           = "/syncnoterpc.SyncnoteService/CreateTeam"
	SyncnoteService_GetTeam_FullMethodName              = "/syncnoterpc.SyncnoteService/GetTeam"
	SyncnoteService_UpdateTeam_FullMethodName           = "/syncnoterpc.SyncnoteService/UpdateTeam"
	SyncnoteService_DeleteTeam_FullMethodName           = "/syncnoterpc.SyncnoteService/DeleteTeam"
	SyncnoteService_JoinTeam_FullMethodName             = "/syncnoterpc.SyncnoteService/JoinTeam"
	SyncnoteService_ExitTeam_FullMethodName             = "/syncnoterpc.SyncnoteService/ExitTeam"
)

// SyncnoteServiceClient is the client API for SyncnoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============ 服务定义 ============
type SyncnoteServiceClient interface {
	CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error)
	GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error)
	UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...grpc.CallOption) (*UpdateNoteResponse, error)
	DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error)
	GrantNotePermission(ctx context.Context, in *GrantNotePermissionRequest, opts ...grpc.CallOption) (*GrantNotePermissionResponse, error)
	RevokeNotePermission(ctx context.Context, in *RevokeNotePermissionRequest, opts ...grpc.CallOption) (*RevokeNotePermissionResponse, error)
	CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error)
	GetTeam(ctx context.Context, in *GetTeamRequest, opts ...grpc.CallOption) (*GetTeamResponse, error)
	UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*UpdateTeamResponse, error)
	DeleteTeam(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*DeleteTeamResponse, error)
	JoinTeam(ctx context.Context, in *JoinTeamRequest, opts ...grpc.CallOption) (*JoinTeamResponse, error)
	ExitTeam(ctx context.Context, in *ExitTeamRequest, opts ...grpc.CallOption) (*ExitTeamResponse, error)
}

type syncnoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncnoteServiceClient(cc grpc.ClientConnInterface) SyncnoteServiceClient {
	return &syncnoteServiceClient{cc}
}

func (c *syncnoteServiceClient) CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNoteResponse)
	err := c.cc.Invoke(ctx, SyncnoteService_CreateNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoteServiceClient) GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNoteResponse)
	err := c.cc.Invoke(ctx, SyncnoteService_GetNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoteServiceClient) UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...grpc.CallOption) (*UpdateNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNoteResponse)
	err := c.cc.Invoke(ctx, SyncnoteService_UpdateNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoteServiceClient) DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNoteResponse)
	err := c.cc.Invoke(ctx, SyncnoteService_DeleteNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoteServiceClient) GrantNotePermission(ctx context.Context, in *GrantNotePermissionRequest, opts ...grpc.CallOption) (*GrantNotePermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantNotePermissionResponse)
	err := c.cc.Invoke(ctx, SyncnoteService_GrantNotePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoteServiceClient) RevokeNotePermission(ctx context.Context, in *RevokeNotePermissionRequest, opts ...grpc.CallOption) (*RevokeNotePermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeNotePermissionResponse)
	err := c.cc.Invoke(ctx, SyncnoteService_RevokeNotePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoteServiceClient) CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTeamResponse)
	err := c.cc.Invoke(ctx, SyncnoteService_CreateTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoteServiceClient) GetTeam(ctx context.Context, in *GetTeamRequest, opts ...grpc.CallOption) (*GetTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamResponse)
	err := c.cc.Invoke(ctx, SyncnoteService_GetTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoteServiceClient) UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*UpdateTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTeamResponse)
	err := c.cc.Invoke(ctx, SyncnoteService_UpdateTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoteServiceClient) DeleteTeam(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*DeleteTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTeamResponse)
	err := c.cc.Invoke(ctx, SyncnoteService_DeleteTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoteServiceClient) JoinTeam(ctx context.Context, in *JoinTeamRequest, opts ...grpc.CallOption) (*JoinTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinTeamResponse)
	err := c.cc.Invoke(ctx, SyncnoteService_JoinTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncnoteServiceClient) ExitTeam(ctx context.Context, in *ExitTeamRequest, opts ...grpc.CallOption) (*ExitTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExitTeamResponse)
	err := c.cc.Invoke(ctx, SyncnoteService_ExitTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncnoteServiceServer is the server API for SyncnoteService service.
// All implementations must embed UnimplementedSyncnoteServiceServer
// for forward compatibility.
//
// ============ 服务定义 ============
type SyncnoteServiceServer interface {
	CreateNote(context.Context, *CreateNoteRequest) (*CreateNoteResponse, error)
	GetNote(context.Context, *GetNoteRequest) (*GetNoteResponse, error)
	UpdateNote(context.Context, *UpdateNoteRequest) (*UpdateNoteResponse, error)
	DeleteNote(context.Context, *DeleteNoteRequest) (*DeleteNoteResponse, error)
	GrantNotePermission(context.Context, *GrantNotePermissionRequest) (*GrantNotePermissionResponse, error)
	RevokeNotePermission(context.Context, *RevokeNotePermissionRequest) (*RevokeNotePermissionResponse, error)
	CreateTeam(context.Context, *CreateTeamRequest) (*CreateTeamResponse, error)
	GetTeam(context.Context, *GetTeamRequest) (*GetTeamResponse, error)
	UpdateTeam(context.Context, *UpdateTeamRequest) (*UpdateTeamResponse, error)
	DeleteTeam(context.Context, *DeleteTeamRequest) (*DeleteTeamResponse, error)
	JoinTeam(context.Context, *JoinTeamRequest) (*JoinTeamResponse, error)
	ExitTeam(context.Context, *ExitTeamRequest) (*ExitTeamResponse, error)
	mustEmbedUnimplementedSyncnoteServiceServer()
}

// UnimplementedSyncnoteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncnoteServiceServer struct{}

func (UnimplementedSyncnoteServiceServer) CreateNote(context.Context, *CreateNoteRequest) (*CreateNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNote not implemented")
}
func (UnimplementedSyncnoteServiceServer) GetNote(context.Context, *GetNoteRequest) (*GetNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNote not implemented")
}
func (UnimplementedSyncnoteServiceServer) UpdateNote(context.Context, *UpdateNoteRequest) (*UpdateNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNote not implemented")
}
func (UnimplementedSyncnoteServiceServer) DeleteNote(context.Context, *DeleteNoteRequest) (*DeleteNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNote not implemented")
}
func (UnimplementedSyncnoteServiceServer) GrantNotePermission(context.Context, *GrantNotePermissionRequest) (*GrantNotePermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantNotePermission not implemented")
}
func (UnimplementedSyncnoteServiceServer) RevokeNotePermission(context.Context, *RevokeNotePermissionRequest) (*RevokeNotePermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeNotePermission not implemented")
}
func (UnimplementedSyncnoteServiceServer) CreateTeam(context.Context, *CreateTeamRequest) (*CreateTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTeam not implemented")
}
func (UnimplementedSyncnoteServiceServer) GetTeam(context.Context, *GetTeamRequest) (*GetTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeam not implemented")
}
func (UnimplementedSyncnoteServiceServer) UpdateTeam(context.Context, *UpdateTeamRequest) (*UpdateTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTeam not implemented")
}
func (UnimplementedSyncnoteServiceServer) DeleteTeam(context.Context, *DeleteTeamRequest) (*DeleteTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTeam not implemented")
}
func (UnimplementedSyncnoteServiceServer) JoinTeam(context.Context, *JoinTeamRequest) (*JoinTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinTeam not implemented")
}
func (UnimplementedSyncnoteServiceServer) ExitTeam(context.Context, *ExitTeamRequest) (*ExitTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExitTeam not implemented")
}
func (UnimplementedSyncnoteServiceServer) mustEmbedUnimplementedSyncnoteServiceServer() {}
func (UnimplementedSyncnoteServiceServer) testEmbeddedByValue()                         {}

// UnsafeSyncnoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncnoteServiceServer will
// result in compilation errors.
type UnsafeSyncnoteServiceServer interface {
	mustEmbedUnimplementedSyncnoteServiceServer()
}

func RegisterSyncnoteServiceServer(s grpc.ServiceRegistrar, srv SyncnoteServiceServer) {
	// If the following call panics, it indicates UnimplementedSyncnoteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncnoteService_ServiceDesc, srv)
}

func _SyncnoteService_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoteServiceServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncnoteService_CreateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoteServiceServer).CreateNote(ctx, req.(*CreateNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncnoteService_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoteServiceServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncnoteService_GetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoteServiceServer).GetNote(ctx, req.(*GetNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncnoteService_UpdateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoteServiceServer).UpdateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncnoteService_UpdateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoteServiceServer).UpdateNote(ctx, req.(*UpdateNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncnoteService_DeleteNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoteServiceServer).DeleteNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncnoteService_DeleteNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoteServiceServer).DeleteNote(ctx, req.(*DeleteNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncnoteService_GrantNotePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantNotePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoteServiceServer).GrantNotePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncnoteService_GrantNotePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoteServiceServer).GrantNotePermission(ctx, req.(*GrantNotePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncnoteService_RevokeNotePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeNotePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoteServiceServer).RevokeNotePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncnoteService_RevokeNotePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoteServiceServer).RevokeNotePermission(ctx, req.(*RevokeNotePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncnoteService_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoteServiceServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncnoteService_CreateTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoteServiceServer).CreateTeam(ctx, req.(*CreateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncnoteService_GetTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoteServiceServer).GetTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncnoteService_GetTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoteServiceServer).GetTeam(ctx, req.(*GetTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncnoteService_UpdateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoteServiceServer).UpdateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncnoteService_UpdateTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoteServiceServer).UpdateTeam(ctx, req.(*UpdateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncnoteService_DeleteTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoteServiceServer).DeleteTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncnoteService_DeleteTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoteServiceServer).DeleteTeam(ctx, req.(*DeleteTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncnoteService_JoinTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoteServiceServer).JoinTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncnoteService_JoinTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoteServiceServer).JoinTeam(ctx, req.(*JoinTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncnoteService_ExitTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExitTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncnoteServiceServer).ExitTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncnoteService_ExitTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncnoteServiceServer).ExitTeam(ctx, req.(*ExitTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncnoteService_ServiceDesc is the grpc.ServiceDesc for SyncnoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncnoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "syncnoterpc.SyncnoteService",
	HandlerType: (*SyncnoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNote",
			Handler:    _SyncnoteService_CreateNote_Handler,
		},
		{
			MethodName: "GetNote",
			Handler:    _SyncnoteService_GetNote_Handler,
		},
		{
			MethodName: "UpdateNote",
			Handler:    _SyncnoteService_UpdateNote_Handler,
		},
		{
			MethodName: "DeleteNote",
			Handler:    _SyncnoteService_DeleteNote_Handler,
		},
		{
			MethodName: "GrantNotePermission",
			Handler:    _SyncnoteService_GrantNotePermission_Handler,
		},
		{
			MethodName: "RevokeNotePermission",
			Handler:    _SyncnoteService_RevokeNotePermission_Handler,
		},
		{
			MethodName: "CreateTeam",
			Handler:    _SyncnoteService_CreateTeam_Handler,
		},
		{
			MethodName: "GetTeam",
			Handler:    _SyncnoteService_GetTeam_Handler,
		},
		{
			MethodName: "UpdateTeam",
			Handler:    _SyncnoteService_UpdateTeam_Handler,
		},
		{
			MethodName: "DeleteTeam",
			Handler:    _SyncnoteService_DeleteTeam_Handler,
		},
		{
			MethodName: "JoinTeam",
			Handler:    _SyncnoteService_JoinTeam_Handler,
		},
		{
			MethodName: "ExitTeam",
			Handler:    _SyncnoteService_ExitTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "syncnote.proto",
}
