// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: syncNoterpc.proto

package syncnoterpcclient

import (
	"context"

	"SyncNote/rpc/pb/syncnoterpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateNoteReq = syncnoterpc.CreateNoteReq
	NoteReq       = syncnoterpc.NoteReq
	NoteResp      = syncnoterpc.NoteResp
	NoteSummary   = syncnoterpc.NoteSummary
	SaveNoteReq   = syncnoterpc.SaveNoteReq
	SaveNoteResp  = syncnoterpc.SaveNoteResp
	UserNotesReq  = syncnoterpc.UserNotesReq
	UserNotesResp = syncnoterpc.UserNotesResp

	Syncnoterpc interface {
		CreateNote(ctx context.Context, in *CreateNoteReq, opts ...grpc.CallOption) (*NoteResp, error)
		GetNote(ctx context.Context, in *NoteReq, opts ...grpc.CallOption) (*NoteResp, error)
		SaveNote(ctx context.Context, in *SaveNoteReq, opts ...grpc.CallOption) (*SaveNoteResp, error)
		GetUserNotes(ctx context.Context, in *UserNotesReq, opts ...grpc.CallOption) (*UserNotesResp, error)
	}

	defaultSyncnoterpc struct {
		cli zrpc.Client
	}
)

func NewSyncnoterpc(cli zrpc.Client) Syncnoterpc {
	return &defaultSyncnoterpc{
		cli: cli,
	}
}

func (m *defaultSyncnoterpc) CreateNote(ctx context.Context, in *CreateNoteReq, opts ...grpc.CallOption) (*NoteResp, error) {
	client := syncnoterpc.NewSyncnoterpcClient(m.cli.Conn())
	return client.CreateNote(ctx, in, opts...)
}

func (m *defaultSyncnoterpc) GetNote(ctx context.Context, in *NoteReq, opts ...grpc.CallOption) (*NoteResp, error) {
	client := syncnoterpc.NewSyncnoterpcClient(m.cli.Conn())
	return client.GetNote(ctx, in, opts...)
}

func (m *defaultSyncnoterpc) SaveNote(ctx context.Context, in *SaveNoteReq, opts ...grpc.CallOption) (*SaveNoteResp, error) {
	client := syncnoterpc.NewSyncnoterpcClient(m.cli.Conn())
	return client.SaveNote(ctx, in, opts...)
}

func (m *defaultSyncnoterpc) GetUserNotes(ctx context.Context, in *UserNotesReq, opts ...grpc.CallOption) (*UserNotesResp, error) {
	client := syncnoterpc.NewSyncnoterpcClient(m.cli.Conn())
	return client.GetUserNotes(ctx, in, opts...)
}
